FROM docker:18

MAINTAINER Viktor Farcic <viktor@farcic.com>

ARG version="0.2.0"
ARG build_date="unknown"
ARG commit_hash="unknown"
ARG vcs_url="unknown"
ARG vcs_branch="unknown"

LABEL org.label-schema.vendor="vfarcic" \
    org.label-schema.name="jenkins-swarm-agent" \
    org.label-schema.description="Jenkins agent based on the Swarm plugin" \
    org.label-schema.usage="/src/README.md" \
    org.label-schema.url="https://github.com/vfarcic/docker-jenkins-slave-dind/blob/master/README.md" \
    org.label-schema.vcs-url=$vcs_url \
    org.label-schema.vcs-branch=$vcs_branch \
    org.label-schema.vcs-ref=$commit_hash \
    org.label-schema.version=$version \
    org.label-schema.schema-version="1.0" \
    org.label-schema.build-date=$build_date

ENV SWARM_CLIENT_VERSION="3.15" \
    DOCKER_COMPOSE_VERSION="1.23.2" \
    COMMAND_OPTIONS="" \
    USER_NAME_SECRET="" \
    PASSWORD_SECRET=""

RUN addgroup -g 121 docker && \
        adduser -S -h /home/otptest -s /bin/sh -G wheel -u 421 otptest && \
        addgroup otptest root && \
        addgroup otptest docker && \
        apk --update --no-cache add tzdata openjdk8-jre python py-pip git openssh ca-certificates openssl curl && \
        echo "Europe/Stockholm" >/etc/timezone && \
        ln -snf /usr/share/zoneinfo/$(cat /etc/timezone) /etc/localtime

USER otptest

RUN curl https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/${SWARM_CLIENT_VERSION}/swarm-client-${SWARM_CLIENT_VERSION}.jar > $HOME/swarm-client-${SWARM_CLIENT_VERSION}.jar && \
        printf "#!/bin/sh \n java -jar $HOME/swarm-client-${SWARM_CLIENT_VERSION}.jar \$*" > $HOME/entrypoint.sh && \
        chmod a+xr $HOME/entrypoint.sh

ENTRYPOINT ["/home/otptest/entrypoint.sh"]
