/*
 *  Warning: Do not edit this file.
 *  Auto-generated by 'beam_makeops'.
 */

case 0: RVAL = never(st); break;
case 1: RVAL = succ(st, var[0], var[1]); break;
case 2: RVAL = succ(st, var[1], var[2]); break;
case 3: RVAL = succ3(st, var[0], var[1]); break;
case 4: RVAL = succ4(st, var[0], var[1]); break;
case 5: RVAL = use_jump_tab(st, var[2], rest_args); break;
case 6: RVAL = mixed_types(st, var[3], rest_args); break;
case 7: RVAL = mixed_types(st, var[2], rest_args); break;
case 8: RVAL = fixed_size_values(st, var[2], rest_args); break;
case 9: RVAL = floats_or_bignums(st, var[2], rest_args); break;
case 10: RVAL = succ(st, var[1], var[3]); break;
case 11: RVAL = succ(st, var[3], var[5]); break;
case 12: RVAL = succ(st, var[4], var[6]); break;
case 13: RVAL = succ(st, var[5], var[7]); break;
case 14: RVAL = succ(st, var[0], var[2]); break;
case 15: RVAL = succ(st, var[1], var[4]); break;
case 16: RVAL = succ(st, var[1], var[5]); break;
case 17: RVAL = is_killed_apply(st, var[2], var[4]); break;
case 18: RVAL = is_killed_by_call_fun(st, var[2], var[4]); break;
case 19: RVAL = is_killed_by_make_fun(st, var[2], var[3]); break;
case 20: RVAL = is_killed(st, var[2], var[4]); break;
case 21: RVAL = is_killed(st, var[2], var[3]); break;
case 22: RVAL = is_killed(st, var[2], var[6]); break;
case 23: RVAL = distinct(st, var[2], var[3]); break;
case 24: RVAL = is_killed(st, var[2], var[5]); break;
case 25: RVAL = is_killed_by_send(st, var[2]); break;
case 26: RVAL = distinct(st, var[1], var[2]); break;
case 27: RVAL = independent_moves(st, var[0], var[1], var[2], var[3]); break;
case 28: RVAL = independent_moves(st, var[2], var[3], var[0], var[1]); break;
case 29: RVAL = smp_mark_target_label(st, var[0]); break;
case 30: RVAL = smp_already_locked(st, var[0]); break;
case 31: RVAL = succ(st, var[2], var[4]); break;
case 32: RVAL = distinct(st, var[2], var[0]); break;
case 33: RVAL = distinct(st, var[4], var[0]); break;
case 34: RVAL = distinct(st, var[4], var[2]); break;
case 35: RVAL = is_killed_by_make_fun(st, var[1], var[3]); break;
case 36: RVAL = binary_too_big(st, var[1]); break;
case 37: RVAL = no_fpe_signals(st); break;
case 38: RVAL = compiled_with_otp_20_or_higher(st); break;
case 39: RVAL = literal_is_map(st, var[0]); break;
case 40: RVAL = map_key_sort(st, var[3], rest_args); break;
case 41: RVAL = map_key_sort(st, var[4], rest_args); break;
case 42: RVAL = is_empty_map(st, var[0]); break;
case 43: RVAL = is_small_map_literal_keys(st, var[2], rest_args); break;
case 44: RVAL = literal_is_map(st, var[1]); break;
case 45: RVAL = map_key_sort(st, var[2], rest_args); break;
case 46: RVAL = negation_is_small(st, var[2]); break;
