/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Thu Nov 21 20:26:55 2019.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "erl_process.h"
#include "erl_nfunc_sched.h"
#include "erl_bif_table.h"
#include "erl_atom_table.h"

Eterm nbif_impl_abs_1(Process *c_p, Eterm *regs)
{
    return abs_1(c_p, regs, (UWord *) bif_export[BIF_abs_1]);
}

Eterm nbif_impl_adler32_1(Process *c_p, Eterm *regs)
{
    return adler32_1(c_p, regs, (UWord *) bif_export[BIF_adler32_1]);
}

Eterm nbif_impl_adler32_2(Process *c_p, Eterm *regs)
{
    return adler32_2(c_p, regs, (UWord *) bif_export[BIF_adler32_2]);
}

Eterm nbif_impl_adler32_combine_3(Process *c_p, Eterm *regs)
{
    return adler32_combine_3(c_p, regs, (UWord *) bif_export[BIF_adler32_combine_3]);
}

Eterm nbif_impl_apply_3(Process *c_p, Eterm *regs)
{
    return apply_3(c_p, regs, (UWord *) bif_export[BIF_apply_3]);
}

Eterm nbif_impl_atom_to_list_1(Process *c_p, Eterm *regs)
{
    return atom_to_list_1(c_p, regs, (UWord *) bif_export[BIF_atom_to_list_1]);
}

Eterm nbif_impl_binary_to_list_1(Process *c_p, Eterm *regs)
{
    return binary_to_list_1(c_p, regs, (UWord *) bif_export[BIF_binary_to_list_1]);
}

Eterm nbif_impl_binary_to_list_3(Process *c_p, Eterm *regs)
{
    return binary_to_list_3(c_p, regs, (UWord *) bif_export[BIF_binary_to_list_3]);
}

Eterm nbif_impl_binary_to_term_1(Process *c_p, Eterm *regs)
{
    return binary_to_term_1(c_p, regs, (UWord *) bif_export[BIF_binary_to_term_1]);
}

Eterm nbif_impl_crc32_1(Process *c_p, Eterm *regs)
{
    return crc32_1(c_p, regs, (UWord *) bif_export[BIF_crc32_1]);
}

Eterm nbif_impl_crc32_2(Process *c_p, Eterm *regs)
{
    return crc32_2(c_p, regs, (UWord *) bif_export[BIF_crc32_2]);
}

Eterm nbif_impl_crc32_combine_3(Process *c_p, Eterm *regs)
{
    return crc32_combine_3(c_p, regs, (UWord *) bif_export[BIF_crc32_combine_3]);
}

Eterm nbif_impl_date_0(Process *c_p, Eterm *regs)
{
    return date_0(c_p, regs, (UWord *) bif_export[BIF_date_0]);
}

Eterm nbif_impl_delete_module_1(Process *c_p, Eterm *regs)
{
    return delete_module_1(c_p, regs, (UWord *) bif_export[BIF_delete_module_1]);
}

Eterm nbif_impl_display_1(Process *c_p, Eterm *regs)
{
    return display_1(c_p, regs, (UWord *) bif_export[BIF_display_1]);
}

Eterm nbif_impl_display_string_1(Process *c_p, Eterm *regs)
{
    return display_string_1(c_p, regs, (UWord *) bif_export[BIF_display_string_1]);
}

Eterm nbif_impl_display_nl_0(Process *c_p, Eterm *regs)
{
    return display_nl_0(c_p, regs, (UWord *) bif_export[BIF_display_nl_0]);
}

Eterm nbif_impl_element_2(Process *c_p, Eterm *regs)
{
    return element_2(c_p, regs, (UWord *) bif_export[BIF_element_2]);
}

Eterm nbif_impl_erase_0(Process *c_p, Eterm *regs)
{
    return erase_0(c_p, regs, (UWord *) bif_export[BIF_erase_0]);
}

Eterm nbif_impl_erase_1(Process *c_p, Eterm *regs)
{
    return erase_1(c_p, regs, (UWord *) bif_export[BIF_erase_1]);
}

Eterm nbif_impl_exit_1(Process *c_p, Eterm *regs)
{
    return exit_1(c_p, regs, (UWord *) bif_export[BIF_exit_1]);
}

Eterm nbif_impl_exit_2(Process *c_p, Eterm *regs)
{
    return exit_2(c_p, regs, (UWord *) bif_export[BIF_exit_2]);
}

Eterm nbif_impl_exit_signal_2(Process *c_p, Eterm *regs)
{
    return exit_signal_2(c_p, regs, (UWord *) bif_export[BIF_exit_signal_2]);
}

Eterm nbif_impl_external_size_1(Process *c_p, Eterm *regs)
{
    return external_size_1(c_p, regs, (UWord *) bif_export[BIF_external_size_1]);
}

Eterm nbif_impl_external_size_2(Process *c_p, Eterm *regs)
{
    return external_size_2(c_p, regs, (UWord *) bif_export[BIF_external_size_2]);
}

Eterm nbif_impl_float_1(Process *c_p, Eterm *regs)
{
    return float_1(c_p, regs, (UWord *) bif_export[BIF_float_1]);
}

Eterm nbif_impl_float_to_list_1(Process *c_p, Eterm *regs)
{
    return float_to_list_1(c_p, regs, (UWord *) bif_export[BIF_float_to_list_1]);
}

Eterm nbif_impl_float_to_list_2(Process *c_p, Eterm *regs)
{
    return float_to_list_2(c_p, regs, (UWord *) bif_export[BIF_float_to_list_2]);
}

Eterm nbif_impl_fun_info_2(Process *c_p, Eterm *regs)
{
    return fun_info_2(c_p, regs, (UWord *) bif_export[BIF_fun_info_2]);
}

Eterm nbif_impl_erts_internal_garbage_collect_1(Process *c_p, Eterm *regs)
{
    return erts_internal_garbage_collect_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_garbage_collect_1]);
}

Eterm nbif_impl_get_0(Process *c_p, Eterm *regs)
{
    return get_0(c_p, regs, (UWord *) bif_export[BIF_get_0]);
}

Eterm nbif_impl_get_1(Process *c_p, Eterm *regs)
{
    return get_1(c_p, regs, (UWord *) bif_export[BIF_get_1]);
}

Eterm nbif_impl_get_keys_1(Process *c_p, Eterm *regs)
{
    return get_keys_1(c_p, regs, (UWord *) bif_export[BIF_get_keys_1]);
}

Eterm nbif_impl_group_leader_0(Process *c_p, Eterm *regs)
{
    return group_leader_0(c_p, regs, (UWord *) bif_export[BIF_group_leader_0]);
}

Eterm nbif_impl_erts_internal_group_leader_2(Process *c_p, Eterm *regs)
{
    return erts_internal_group_leader_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_group_leader_2]);
}

Eterm nbif_impl_erts_internal_group_leader_3(Process *c_p, Eterm *regs)
{
    return erts_internal_group_leader_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_group_leader_3]);
}

Eterm nbif_impl_halt_2(Process *c_p, Eterm *regs)
{
    return halt_2(c_p, regs, (UWord *) bif_export[BIF_halt_2]);
}

Eterm nbif_impl_phash_2(Process *c_p, Eterm *regs)
{
    return phash_2(c_p, regs, (UWord *) bif_export[BIF_phash_2]);
}

Eterm nbif_impl_phash2_1(Process *c_p, Eterm *regs)
{
    return phash2_1(c_p, regs, (UWord *) bif_export[BIF_phash2_1]);
}

Eterm nbif_impl_phash2_2(Process *c_p, Eterm *regs)
{
    return phash2_2(c_p, regs, (UWord *) bif_export[BIF_phash2_2]);
}

Eterm nbif_impl_hd_1(Process *c_p, Eterm *regs)
{
    return hd_1(c_p, regs, (UWord *) bif_export[BIF_hd_1]);
}

Eterm nbif_impl_integer_to_list_1(Process *c_p, Eterm *regs)
{
    return integer_to_list_1(c_p, regs, (UWord *) bif_export[BIF_integer_to_list_1]);
}

Eterm nbif_impl_is_alive_0(Process *c_p, Eterm *regs)
{
    return is_alive_0(c_p, regs, (UWord *) bif_export[BIF_is_alive_0]);
}

Eterm nbif_impl_length_1(Process *c_p, Eterm *regs)
{
    return length_1(c_p, regs, (UWord *) bif_export[BIF_length_1]);
}

Eterm nbif_impl_link_1(Process *c_p, Eterm *regs)
{
    return link_1(c_p, regs, (UWord *) bif_export[BIF_link_1]);
}

Eterm nbif_impl_list_to_atom_1(Process *c_p, Eterm *regs)
{
    return list_to_atom_1(c_p, regs, (UWord *) bif_export[BIF_list_to_atom_1]);
}

Eterm nbif_impl_list_to_binary_1(Process *c_p, Eterm *regs)
{
    return list_to_binary_1(c_p, regs, (UWord *) bif_export[BIF_list_to_binary_1]);
}

Eterm nbif_impl_list_to_float_1(Process *c_p, Eterm *regs)
{
    return list_to_float_1(c_p, regs, (UWord *) bif_export[BIF_list_to_float_1]);
}

Eterm nbif_impl_list_to_integer_1(Process *c_p, Eterm *regs)
{
    return list_to_integer_1(c_p, regs, (UWord *) bif_export[BIF_list_to_integer_1]);
}

Eterm nbif_impl_list_to_pid_1(Process *c_p, Eterm *regs)
{
    return list_to_pid_1(c_p, regs, (UWord *) bif_export[BIF_list_to_pid_1]);
}

Eterm nbif_impl_list_to_port_1(Process *c_p, Eterm *regs)
{
    return list_to_port_1(c_p, regs, (UWord *) bif_export[BIF_list_to_port_1]);
}

Eterm nbif_impl_list_to_ref_1(Process *c_p, Eterm *regs)
{
    return list_to_ref_1(c_p, regs, (UWord *) bif_export[BIF_list_to_ref_1]);
}

Eterm nbif_impl_list_to_tuple_1(Process *c_p, Eterm *regs)
{
    return list_to_tuple_1(c_p, regs, (UWord *) bif_export[BIF_list_to_tuple_1]);
}

Eterm nbif_impl_loaded_0(Process *c_p, Eterm *regs)
{
    return loaded_0(c_p, regs, (UWord *) bif_export[BIF_loaded_0]);
}

Eterm nbif_impl_localtime_0(Process *c_p, Eterm *regs)
{
    return localtime_0(c_p, regs, (UWord *) bif_export[BIF_localtime_0]);
}

Eterm nbif_impl_localtime_to_universaltime_2(Process *c_p, Eterm *regs)
{
    return localtime_to_universaltime_2(c_p, regs, (UWord *) bif_export[BIF_localtime_to_universaltime_2]);
}

Eterm nbif_impl_make_ref_0(Process *c_p, Eterm *regs)
{
    return make_ref_0(c_p, regs, (UWord *) bif_export[BIF_make_ref_0]);
}

Eterm nbif_impl_unique_integer_0(Process *c_p, Eterm *regs)
{
    return unique_integer_0(c_p, regs, (UWord *) bif_export[BIF_unique_integer_0]);
}

Eterm nbif_impl_unique_integer_1(Process *c_p, Eterm *regs)
{
    return unique_integer_1(c_p, regs, (UWord *) bif_export[BIF_unique_integer_1]);
}

Eterm nbif_impl_md5_1(Process *c_p, Eterm *regs)
{
    return md5_1(c_p, regs, (UWord *) bif_export[BIF_md5_1]);
}

Eterm nbif_impl_md5_init_0(Process *c_p, Eterm *regs)
{
    return md5_init_0(c_p, regs, (UWord *) bif_export[BIF_md5_init_0]);
}

Eterm nbif_impl_md5_update_2(Process *c_p, Eterm *regs)
{
    return md5_update_2(c_p, regs, (UWord *) bif_export[BIF_md5_update_2]);
}

Eterm nbif_impl_md5_final_1(Process *c_p, Eterm *regs)
{
    return md5_final_1(c_p, regs, (UWord *) bif_export[BIF_md5_final_1]);
}

Eterm nbif_impl_module_loaded_1(Process *c_p, Eterm *regs)
{
    return module_loaded_1(c_p, regs, (UWord *) bif_export[BIF_module_loaded_1]);
}

Eterm nbif_impl_function_exported_3(Process *c_p, Eterm *regs)
{
    return function_exported_3(c_p, regs, (UWord *) bif_export[BIF_function_exported_3]);
}

Eterm nbif_impl_monitor_node_2(Process *c_p, Eterm *regs)
{
    return monitor_node_2(c_p, regs, (UWord *) bif_export[BIF_monitor_node_2]);
}

Eterm nbif_impl_monitor_node_3(Process *c_p, Eterm *regs)
{
    return monitor_node_3(c_p, regs, (UWord *) bif_export[BIF_monitor_node_3]);
}

Eterm nbif_impl_node_1(Process *c_p, Eterm *regs)
{
    return node_1(c_p, regs, (UWord *) bif_export[BIF_node_1]);
}

Eterm nbif_impl_node_0(Process *c_p, Eterm *regs)
{
    return node_0(c_p, regs, (UWord *) bif_export[BIF_node_0]);
}

Eterm nbif_impl_nodes_1(Process *c_p, Eterm *regs)
{
    return nodes_1(c_p, regs, (UWord *) bif_export[BIF_nodes_1]);
}

Eterm nbif_impl_now_0(Process *c_p, Eterm *regs)
{
    return now_0(c_p, regs, (UWord *) bif_export[BIF_now_0]);
}

Eterm nbif_impl_monotonic_time_0(Process *c_p, Eterm *regs)
{
    return monotonic_time_0(c_p, regs, (UWord *) bif_export[BIF_monotonic_time_0]);
}

Eterm nbif_impl_monotonic_time_1(Process *c_p, Eterm *regs)
{
    return monotonic_time_1(c_p, regs, (UWord *) bif_export[BIF_monotonic_time_1]);
}

Eterm nbif_impl_system_time_0(Process *c_p, Eterm *regs)
{
    return system_time_0(c_p, regs, (UWord *) bif_export[BIF_system_time_0]);
}

Eterm nbif_impl_system_time_1(Process *c_p, Eterm *regs)
{
    return system_time_1(c_p, regs, (UWord *) bif_export[BIF_system_time_1]);
}

Eterm nbif_impl_time_offset_0(Process *c_p, Eterm *regs)
{
    return time_offset_0(c_p, regs, (UWord *) bif_export[BIF_time_offset_0]);
}

Eterm nbif_impl_time_offset_1(Process *c_p, Eterm *regs)
{
    return time_offset_1(c_p, regs, (UWord *) bif_export[BIF_time_offset_1]);
}

Eterm nbif_impl_timestamp_0(Process *c_p, Eterm *regs)
{
    return timestamp_0(c_p, regs, (UWord *) bif_export[BIF_timestamp_0]);
}

Eterm nbif_impl_erts_internal_open_port_2(Process *c_p, Eterm *regs)
{
    return erts_internal_open_port_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_open_port_2]);
}

Eterm nbif_impl_pid_to_list_1(Process *c_p, Eterm *regs)
{
    return pid_to_list_1(c_p, regs, (UWord *) bif_export[BIF_pid_to_list_1]);
}

Eterm nbif_impl_ports_0(Process *c_p, Eterm *regs)
{
    return ports_0(c_p, regs, (UWord *) bif_export[BIF_ports_0]);
}

Eterm nbif_impl_pre_loaded_0(Process *c_p, Eterm *regs)
{
    return pre_loaded_0(c_p, regs, (UWord *) bif_export[BIF_pre_loaded_0]);
}

Eterm nbif_impl_process_flag_2(Process *c_p, Eterm *regs)
{
    return process_flag_2(c_p, regs, (UWord *) bif_export[BIF_process_flag_2]);
}

Eterm nbif_impl_erts_internal_process_flag_3(Process *c_p, Eterm *regs)
{
    return erts_internal_process_flag_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_process_flag_3]);
}

Eterm nbif_impl_process_info_1(Process *c_p, Eterm *regs)
{
    return process_info_1(c_p, regs, (UWord *) bif_export[BIF_process_info_1]);
}

Eterm nbif_impl_process_info_2(Process *c_p, Eterm *regs)
{
    return process_info_2(c_p, regs, (UWord *) bif_export[BIF_process_info_2]);
}

Eterm nbif_impl_processes_0(Process *c_p, Eterm *regs)
{
    return processes_0(c_p, regs, (UWord *) bif_export[BIF_processes_0]);
}

Eterm nbif_impl_put_2(Process *c_p, Eterm *regs)
{
    return put_2(c_p, regs, (UWord *) bif_export[BIF_put_2]);
}

Eterm nbif_impl_register_2(Process *c_p, Eterm *regs)
{
    return register_2(c_p, regs, (UWord *) bif_export[BIF_register_2]);
}

Eterm nbif_impl_registered_0(Process *c_p, Eterm *regs)
{
    return registered_0(c_p, regs, (UWord *) bif_export[BIF_registered_0]);
}

Eterm nbif_impl_round_1(Process *c_p, Eterm *regs)
{
    return round_1(c_p, regs, (UWord *) bif_export[BIF_round_1]);
}

Eterm nbif_impl_self_0(Process *c_p, Eterm *regs)
{
    return self_0(c_p, regs, (UWord *) bif_export[BIF_self_0]);
}

Eterm nbif_impl_setelement_3(Process *c_p, Eterm *regs)
{
    return setelement_3(c_p, regs, (UWord *) bif_export[BIF_setelement_3]);
}

Eterm nbif_impl_size_1(Process *c_p, Eterm *regs)
{
    return size_1(c_p, regs, (UWord *) bif_export[BIF_size_1]);
}

Eterm nbif_impl_spawn_3(Process *c_p, Eterm *regs)
{
    return spawn_3(c_p, regs, (UWord *) bif_export[BIF_spawn_3]);
}

Eterm nbif_impl_spawn_link_3(Process *c_p, Eterm *regs)
{
    return spawn_link_3(c_p, regs, (UWord *) bif_export[BIF_spawn_link_3]);
}

Eterm nbif_impl_split_binary_2(Process *c_p, Eterm *regs)
{
    return split_binary_2(c_p, regs, (UWord *) bif_export[BIF_split_binary_2]);
}

Eterm nbif_impl_statistics_1(Process *c_p, Eterm *regs)
{
    return statistics_1(c_p, regs, (UWord *) bif_export[BIF_statistics_1]);
}

Eterm nbif_impl_term_to_binary_1(Process *c_p, Eterm *regs)
{
    return term_to_binary_1(c_p, regs, (UWord *) bif_export[BIF_term_to_binary_1]);
}

Eterm nbif_impl_term_to_binary_2(Process *c_p, Eterm *regs)
{
    return term_to_binary_2(c_p, regs, (UWord *) bif_export[BIF_term_to_binary_2]);
}

Eterm nbif_impl_throw_1(Process *c_p, Eterm *regs)
{
    return throw_1(c_p, regs, (UWord *) bif_export[BIF_throw_1]);
}

Eterm nbif_impl_time_0(Process *c_p, Eterm *regs)
{
    return time_0(c_p, regs, (UWord *) bif_export[BIF_time_0]);
}

Eterm nbif_impl_tl_1(Process *c_p, Eterm *regs)
{
    return tl_1(c_p, regs, (UWord *) bif_export[BIF_tl_1]);
}

Eterm nbif_impl_trunc_1(Process *c_p, Eterm *regs)
{
    return trunc_1(c_p, regs, (UWord *) bif_export[BIF_trunc_1]);
}

Eterm nbif_impl_tuple_to_list_1(Process *c_p, Eterm *regs)
{
    return tuple_to_list_1(c_p, regs, (UWord *) bif_export[BIF_tuple_to_list_1]);
}

Eterm nbif_impl_universaltime_0(Process *c_p, Eterm *regs)
{
    return universaltime_0(c_p, regs, (UWord *) bif_export[BIF_universaltime_0]);
}

Eterm nbif_impl_universaltime_to_localtime_1(Process *c_p, Eterm *regs)
{
    return universaltime_to_localtime_1(c_p, regs, (UWord *) bif_export[BIF_universaltime_to_localtime_1]);
}

Eterm nbif_impl_unlink_1(Process *c_p, Eterm *regs)
{
    return unlink_1(c_p, regs, (UWord *) bif_export[BIF_unlink_1]);
}

Eterm nbif_impl_unregister_1(Process *c_p, Eterm *regs)
{
    return unregister_1(c_p, regs, (UWord *) bif_export[BIF_unregister_1]);
}

Eterm nbif_impl_whereis_1(Process *c_p, Eterm *regs)
{
    return whereis_1(c_p, regs, (UWord *) bif_export[BIF_whereis_1]);
}

Eterm nbif_impl_spawn_opt_1(Process *c_p, Eterm *regs)
{
    return spawn_opt_1(c_p, regs, (UWord *) bif_export[BIF_spawn_opt_1]);
}

Eterm nbif_impl_setnode_2(Process *c_p, Eterm *regs)
{
    return setnode_2(c_p, regs, (UWord *) bif_export[BIF_setnode_2]);
}

Eterm nbif_impl_dist_get_stat_1(Process *c_p, Eterm *regs)
{
    return dist_get_stat_1(c_p, regs, (UWord *) bif_export[BIF_dist_get_stat_1]);
}

Eterm nbif_impl_dist_ctrl_input_handler_2(Process *c_p, Eterm *regs)
{
    return dist_ctrl_input_handler_2(c_p, regs, (UWord *) bif_export[BIF_dist_ctrl_input_handler_2]);
}

Eterm nbif_impl_dist_ctrl_put_data_2(Process *c_p, Eterm *regs)
{
    return dist_ctrl_put_data_2(c_p, regs, (UWord *) bif_export[BIF_dist_ctrl_put_data_2]);
}

Eterm nbif_impl_dist_ctrl_get_data_1(Process *c_p, Eterm *regs)
{
    return dist_ctrl_get_data_1(c_p, regs, (UWord *) bif_export[BIF_dist_ctrl_get_data_1]);
}

Eterm nbif_impl_dist_ctrl_get_data_notification_1(Process *c_p, Eterm *regs)
{
    return dist_ctrl_get_data_notification_1(c_p, regs, (UWord *) bif_export[BIF_dist_ctrl_get_data_notification_1]);
}

Eterm nbif_impl_dist_ctrl_get_opt_2(Process *c_p, Eterm *regs)
{
    return dist_ctrl_get_opt_2(c_p, regs, (UWord *) bif_export[BIF_dist_ctrl_get_opt_2]);
}

Eterm nbif_impl_dist_ctrl_set_opt_3(Process *c_p, Eterm *regs)
{
    return dist_ctrl_set_opt_3(c_p, regs, (UWord *) bif_export[BIF_dist_ctrl_set_opt_3]);
}

Eterm nbif_impl_erts_internal_port_info_1(Process *c_p, Eterm *regs)
{
    return erts_internal_port_info_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_info_1]);
}

Eterm nbif_impl_erts_internal_port_info_2(Process *c_p, Eterm *regs)
{
    return erts_internal_port_info_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_info_2]);
}

Eterm nbif_impl_erts_internal_port_call_3(Process *c_p, Eterm *regs)
{
    return erts_internal_port_call_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_call_3]);
}

Eterm nbif_impl_erts_internal_port_command_3(Process *c_p, Eterm *regs)
{
    return erts_internal_port_command_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_command_3]);
}

Eterm nbif_impl_erts_internal_port_control_3(Process *c_p, Eterm *regs)
{
    return erts_internal_port_control_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_control_3]);
}

Eterm nbif_impl_erts_internal_port_close_1(Process *c_p, Eterm *regs)
{
    return erts_internal_port_close_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_close_1]);
}

Eterm nbif_impl_erts_internal_port_connect_2(Process *c_p, Eterm *regs)
{
    return erts_internal_port_connect_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_port_connect_2]);
}

Eterm nbif_impl_erts_internal_request_system_task_3(Process *c_p, Eterm *regs)
{
    return erts_internal_request_system_task_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_request_system_task_3]);
}

Eterm nbif_impl_erts_internal_request_system_task_4(Process *c_p, Eterm *regs)
{
    return erts_internal_request_system_task_4(c_p, regs, (UWord *) bif_export[BIF_erts_internal_request_system_task_4]);
}

Eterm nbif_impl_erts_internal_check_process_code_1(Process *c_p, Eterm *regs)
{
    return erts_internal_check_process_code_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_check_process_code_1]);
}

Eterm nbif_impl_erts_internal_map_to_tuple_keys_1(Process *c_p, Eterm *regs)
{
    return erts_internal_map_to_tuple_keys_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_map_to_tuple_keys_1]);
}

Eterm nbif_impl_erts_internal_term_type_1(Process *c_p, Eterm *regs)
{
    return erts_internal_term_type_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_term_type_1]);
}

Eterm nbif_impl_erts_internal_map_hashmap_children_1(Process *c_p, Eterm *regs)
{
    return erts_internal_map_hashmap_children_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_map_hashmap_children_1]);
}

Eterm nbif_impl_erts_internal_time_unit_0(Process *c_p, Eterm *regs)
{
    return erts_internal_time_unit_0(c_p, regs, (UWord *) bif_export[BIF_erts_internal_time_unit_0]);
}

Eterm nbif_impl_erts_internal_perf_counter_unit_0(Process *c_p, Eterm *regs)
{
    return erts_internal_perf_counter_unit_0(c_p, regs, (UWord *) bif_export[BIF_erts_internal_perf_counter_unit_0]);
}

Eterm nbif_impl_erts_internal_is_system_process_1(Process *c_p, Eterm *regs)
{
    return erts_internal_is_system_process_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_is_system_process_1]);
}

Eterm nbif_impl_erts_internal_system_check_1(Process *c_p, Eterm *regs)
{
    return erts_internal_system_check_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_system_check_1]);
}

Eterm nbif_impl_erts_internal_release_literal_area_switch_0(Process *c_p, Eterm *regs)
{
    return erts_internal_release_literal_area_switch_0(c_p, regs, (UWord *) bif_export[BIF_erts_internal_release_literal_area_switch_0]);
}

Eterm nbif_impl_erts_internal_scheduler_wall_time_1(Process *c_p, Eterm *regs)
{
    return erts_internal_scheduler_wall_time_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_scheduler_wall_time_1]);
}

Eterm nbif_impl_erts_internal_dirty_process_handle_signals_1(Process *c_p, Eterm *regs)
{
    return erts_internal_dirty_process_handle_signals_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_dirty_process_handle_signals_1]);
}

Eterm nbif_impl_erts_internal_create_dist_channel_4(Process *c_p, Eterm *regs)
{
    return erts_internal_create_dist_channel_4(c_p, regs, (UWord *) bif_export[BIF_erts_internal_create_dist_channel_4]);
}

Eterm nbif_impl_erts_internal_ets_super_user_1(Process *c_p, Eterm *regs)
{
    return erts_internal_ets_super_user_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_ets_super_user_1]);
}

Eterm nbif_impl_port_set_data_2(Process *c_p, Eterm *regs)
{
    return port_set_data_2(c_p, regs, (UWord *) bif_export[BIF_port_set_data_2]);
}

Eterm nbif_impl_port_get_data_1(Process *c_p, Eterm *regs)
{
    return port_get_data_1(c_p, regs, (UWord *) bif_export[BIF_port_get_data_1]);
}

Eterm nbif_impl_erts_internal_trace_pattern_3(Process *c_p, Eterm *regs)
{
    return erts_internal_trace_pattern_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_trace_pattern_3]);
}

Eterm nbif_impl_erts_internal_trace_3(Process *c_p, Eterm *regs)
{
    return erts_internal_trace_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_trace_3]);
}

Eterm nbif_impl_trace_info_2(Process *c_p, Eterm *regs)
{
    return trace_info_2(c_p, regs, (UWord *) bif_export[BIF_trace_info_2]);
}

Eterm nbif_impl_trace_delivered_1(Process *c_p, Eterm *regs)
{
    return trace_delivered_1(c_p, regs, (UWord *) bif_export[BIF_trace_delivered_1]);
}

Eterm nbif_impl_seq_trace_2(Process *c_p, Eterm *regs)
{
    return seq_trace_2(c_p, regs, (UWord *) bif_export[BIF_seq_trace_2]);
}

Eterm nbif_impl_seq_trace_info_1(Process *c_p, Eterm *regs)
{
    return seq_trace_info_1(c_p, regs, (UWord *) bif_export[BIF_seq_trace_info_1]);
}

Eterm nbif_impl_seq_trace_print_1(Process *c_p, Eterm *regs)
{
    return seq_trace_print_1(c_p, regs, (UWord *) bif_export[BIF_seq_trace_print_1]);
}

Eterm nbif_impl_seq_trace_print_2(Process *c_p, Eterm *regs)
{
    return seq_trace_print_2(c_p, regs, (UWord *) bif_export[BIF_seq_trace_print_2]);
}

Eterm nbif_impl_erts_internal_suspend_process_2(Process *c_p, Eterm *regs)
{
    return erts_internal_suspend_process_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_suspend_process_2]);
}

Eterm nbif_impl_resume_process_1(Process *c_p, Eterm *regs)
{
    return resume_process_1(c_p, regs, (UWord *) bif_export[BIF_resume_process_1]);
}

Eterm nbif_impl_erts_internal_process_display_2(Process *c_p, Eterm *regs)
{
    return erts_internal_process_display_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_process_display_2]);
}

Eterm nbif_impl_bump_reductions_1(Process *c_p, Eterm *regs)
{
    return bump_reductions_1(c_p, regs, (UWord *) bif_export[BIF_bump_reductions_1]);
}

Eterm nbif_impl_math_cos_1(Process *c_p, Eterm *regs)
{
    return math_cos_1(c_p, regs, (UWord *) bif_export[BIF_math_cos_1]);
}

Eterm nbif_impl_math_cosh_1(Process *c_p, Eterm *regs)
{
    return math_cosh_1(c_p, regs, (UWord *) bif_export[BIF_math_cosh_1]);
}

Eterm nbif_impl_math_sin_1(Process *c_p, Eterm *regs)
{
    return math_sin_1(c_p, regs, (UWord *) bif_export[BIF_math_sin_1]);
}

Eterm nbif_impl_math_sinh_1(Process *c_p, Eterm *regs)
{
    return math_sinh_1(c_p, regs, (UWord *) bif_export[BIF_math_sinh_1]);
}

Eterm nbif_impl_math_tan_1(Process *c_p, Eterm *regs)
{
    return math_tan_1(c_p, regs, (UWord *) bif_export[BIF_math_tan_1]);
}

Eterm nbif_impl_math_tanh_1(Process *c_p, Eterm *regs)
{
    return math_tanh_1(c_p, regs, (UWord *) bif_export[BIF_math_tanh_1]);
}

Eterm nbif_impl_math_acos_1(Process *c_p, Eterm *regs)
{
    return math_acos_1(c_p, regs, (UWord *) bif_export[BIF_math_acos_1]);
}

Eterm nbif_impl_math_acosh_1(Process *c_p, Eterm *regs)
{
    return math_acosh_1(c_p, regs, (UWord *) bif_export[BIF_math_acosh_1]);
}

Eterm nbif_impl_math_asin_1(Process *c_p, Eterm *regs)
{
    return math_asin_1(c_p, regs, (UWord *) bif_export[BIF_math_asin_1]);
}

Eterm nbif_impl_math_asinh_1(Process *c_p, Eterm *regs)
{
    return math_asinh_1(c_p, regs, (UWord *) bif_export[BIF_math_asinh_1]);
}

Eterm nbif_impl_math_atan_1(Process *c_p, Eterm *regs)
{
    return math_atan_1(c_p, regs, (UWord *) bif_export[BIF_math_atan_1]);
}

Eterm nbif_impl_math_atanh_1(Process *c_p, Eterm *regs)
{
    return math_atanh_1(c_p, regs, (UWord *) bif_export[BIF_math_atanh_1]);
}

Eterm nbif_impl_math_erf_1(Process *c_p, Eterm *regs)
{
    return math_erf_1(c_p, regs, (UWord *) bif_export[BIF_math_erf_1]);
}

Eterm nbif_impl_math_erfc_1(Process *c_p, Eterm *regs)
{
    return math_erfc_1(c_p, regs, (UWord *) bif_export[BIF_math_erfc_1]);
}

Eterm nbif_impl_math_exp_1(Process *c_p, Eterm *regs)
{
    return math_exp_1(c_p, regs, (UWord *) bif_export[BIF_math_exp_1]);
}

Eterm nbif_impl_math_log_1(Process *c_p, Eterm *regs)
{
    return math_log_1(c_p, regs, (UWord *) bif_export[BIF_math_log_1]);
}

Eterm nbif_impl_math_log2_1(Process *c_p, Eterm *regs)
{
    return math_log2_1(c_p, regs, (UWord *) bif_export[BIF_math_log2_1]);
}

Eterm nbif_impl_math_log10_1(Process *c_p, Eterm *regs)
{
    return math_log10_1(c_p, regs, (UWord *) bif_export[BIF_math_log10_1]);
}

Eterm nbif_impl_math_sqrt_1(Process *c_p, Eterm *regs)
{
    return math_sqrt_1(c_p, regs, (UWord *) bif_export[BIF_math_sqrt_1]);
}

Eterm nbif_impl_math_atan2_2(Process *c_p, Eterm *regs)
{
    return math_atan2_2(c_p, regs, (UWord *) bif_export[BIF_math_atan2_2]);
}

Eterm nbif_impl_math_pow_2(Process *c_p, Eterm *regs)
{
    return math_pow_2(c_p, regs, (UWord *) bif_export[BIF_math_pow_2]);
}

Eterm nbif_impl_start_timer_3(Process *c_p, Eterm *regs)
{
    return start_timer_3(c_p, regs, (UWord *) bif_export[BIF_start_timer_3]);
}

Eterm nbif_impl_start_timer_4(Process *c_p, Eterm *regs)
{
    return start_timer_4(c_p, regs, (UWord *) bif_export[BIF_start_timer_4]);
}

Eterm nbif_impl_send_after_3(Process *c_p, Eterm *regs)
{
    return send_after_3(c_p, regs, (UWord *) bif_export[BIF_send_after_3]);
}

Eterm nbif_impl_send_after_4(Process *c_p, Eterm *regs)
{
    return send_after_4(c_p, regs, (UWord *) bif_export[BIF_send_after_4]);
}

Eterm nbif_impl_cancel_timer_1(Process *c_p, Eterm *regs)
{
    return cancel_timer_1(c_p, regs, (UWord *) bif_export[BIF_cancel_timer_1]);
}

Eterm nbif_impl_cancel_timer_2(Process *c_p, Eterm *regs)
{
    return cancel_timer_2(c_p, regs, (UWord *) bif_export[BIF_cancel_timer_2]);
}

Eterm nbif_impl_read_timer_1(Process *c_p, Eterm *regs)
{
    return read_timer_1(c_p, regs, (UWord *) bif_export[BIF_read_timer_1]);
}

Eterm nbif_impl_read_timer_2(Process *c_p, Eterm *regs)
{
    return read_timer_2(c_p, regs, (UWord *) bif_export[BIF_read_timer_2]);
}

Eterm nbif_impl_make_tuple_2(Process *c_p, Eterm *regs)
{
    return make_tuple_2(c_p, regs, (UWord *) bif_export[BIF_make_tuple_2]);
}

Eterm nbif_impl_append_element_2(Process *c_p, Eterm *regs)
{
    return append_element_2(c_p, regs, (UWord *) bif_export[BIF_append_element_2]);
}

Eterm nbif_impl_make_tuple_3(Process *c_p, Eterm *regs)
{
    return make_tuple_3(c_p, regs, (UWord *) bif_export[BIF_make_tuple_3]);
}

Eterm nbif_impl_system_flag_2(Process *c_p, Eterm *regs)
{
    return system_flag_2(c_p, regs, (UWord *) bif_export[BIF_system_flag_2]);
}

Eterm nbif_impl_system_info_1(Process *c_p, Eterm *regs)
{
    return system_info_1(c_p, regs, (UWord *) bif_export[BIF_system_info_1]);
}

Eterm nbif_impl_system_monitor_0(Process *c_p, Eterm *regs)
{
    return system_monitor_0(c_p, regs, (UWord *) bif_export[BIF_system_monitor_0]);
}

Eterm nbif_impl_system_monitor_1(Process *c_p, Eterm *regs)
{
    return system_monitor_1(c_p, regs, (UWord *) bif_export[BIF_system_monitor_1]);
}

Eterm nbif_impl_system_monitor_2(Process *c_p, Eterm *regs)
{
    return system_monitor_2(c_p, regs, (UWord *) bif_export[BIF_system_monitor_2]);
}

Eterm nbif_impl_system_profile_2(Process *c_p, Eterm *regs)
{
    return system_profile_2(c_p, regs, (UWord *) bif_export[BIF_system_profile_2]);
}

Eterm nbif_impl_system_profile_0(Process *c_p, Eterm *regs)
{
    return system_profile_0(c_p, regs, (UWord *) bif_export[BIF_system_profile_0]);
}

Eterm nbif_impl_ref_to_list_1(Process *c_p, Eterm *regs)
{
    return ref_to_list_1(c_p, regs, (UWord *) bif_export[BIF_ref_to_list_1]);
}

Eterm nbif_impl_port_to_list_1(Process *c_p, Eterm *regs)
{
    return port_to_list_1(c_p, regs, (UWord *) bif_export[BIF_port_to_list_1]);
}

Eterm nbif_impl_fun_to_list_1(Process *c_p, Eterm *regs)
{
    return fun_to_list_1(c_p, regs, (UWord *) bif_export[BIF_fun_to_list_1]);
}

Eterm nbif_impl_monitor_2(Process *c_p, Eterm *regs)
{
    return monitor_2(c_p, regs, (UWord *) bif_export[BIF_monitor_2]);
}

Eterm nbif_impl_demonitor_1(Process *c_p, Eterm *regs)
{
    return demonitor_1(c_p, regs, (UWord *) bif_export[BIF_demonitor_1]);
}

Eterm nbif_impl_demonitor_2(Process *c_p, Eterm *regs)
{
    return demonitor_2(c_p, regs, (UWord *) bif_export[BIF_demonitor_2]);
}

Eterm nbif_impl_is_process_alive_1(Process *c_p, Eterm *regs)
{
    return is_process_alive_1(c_p, regs, (UWord *) bif_export[BIF_is_process_alive_1]);
}

Eterm nbif_impl_erts_internal_is_process_alive_2(Process *c_p, Eterm *regs)
{
    return erts_internal_is_process_alive_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_is_process_alive_2]);
}

Eterm nbif_impl_error_1(Process *c_p, Eterm *regs)
{
    return error_1(c_p, regs, (UWord *) bif_export[BIF_error_1]);
}

Eterm nbif_impl_error_2(Process *c_p, Eterm *regs)
{
    return error_2(c_p, regs, (UWord *) bif_export[BIF_error_2]);
}

Eterm nbif_impl_raise_3(Process *c_p, Eterm *regs)
{
    return raise_3(c_p, regs, (UWord *) bif_export[BIF_raise_3]);
}

Eterm nbif_impl_get_stacktrace_0(Process *c_p, Eterm *regs)
{
    return get_stacktrace_0(c_p, regs, (UWord *) bif_export[BIF_get_stacktrace_0]);
}

Eterm nbif_impl_is_builtin_3(Process *c_p, Eterm *regs)
{
    return is_builtin_3(c_p, regs, (UWord *) bif_export[BIF_is_builtin_3]);
}

Eterm nbif_impl_and_2(Process *c_p, Eterm *regs)
{
    return and_2(c_p, regs, (UWord *) bif_export[BIF_and_2]);
}

Eterm nbif_impl_or_2(Process *c_p, Eterm *regs)
{
    return or_2(c_p, regs, (UWord *) bif_export[BIF_or_2]);
}

Eterm nbif_impl_xor_2(Process *c_p, Eterm *regs)
{
    return xor_2(c_p, regs, (UWord *) bif_export[BIF_xor_2]);
}

Eterm nbif_impl_not_1(Process *c_p, Eterm *regs)
{
    return not_1(c_p, regs, (UWord *) bif_export[BIF_not_1]);
}

Eterm nbif_impl_sgt_2(Process *c_p, Eterm *regs)
{
    return sgt_2(c_p, regs, (UWord *) bif_export[BIF_sgt_2]);
}

Eterm nbif_impl_sge_2(Process *c_p, Eterm *regs)
{
    return sge_2(c_p, regs, (UWord *) bif_export[BIF_sge_2]);
}

Eterm nbif_impl_slt_2(Process *c_p, Eterm *regs)
{
    return slt_2(c_p, regs, (UWord *) bif_export[BIF_slt_2]);
}

Eterm nbif_impl_sle_2(Process *c_p, Eterm *regs)
{
    return sle_2(c_p, regs, (UWord *) bif_export[BIF_sle_2]);
}

Eterm nbif_impl_seq_2(Process *c_p, Eterm *regs)
{
    return seq_2(c_p, regs, (UWord *) bif_export[BIF_seq_2]);
}

Eterm nbif_impl_seqeq_2(Process *c_p, Eterm *regs)
{
    return seqeq_2(c_p, regs, (UWord *) bif_export[BIF_seqeq_2]);
}

Eterm nbif_impl_sneq_2(Process *c_p, Eterm *regs)
{
    return sneq_2(c_p, regs, (UWord *) bif_export[BIF_sneq_2]);
}

Eterm nbif_impl_sneqeq_2(Process *c_p, Eterm *regs)
{
    return sneqeq_2(c_p, regs, (UWord *) bif_export[BIF_sneqeq_2]);
}

Eterm nbif_impl_splus_2(Process *c_p, Eterm *regs)
{
    return splus_2(c_p, regs, (UWord *) bif_export[BIF_splus_2]);
}

Eterm nbif_impl_sminus_2(Process *c_p, Eterm *regs)
{
    return sminus_2(c_p, regs, (UWord *) bif_export[BIF_sminus_2]);
}

Eterm nbif_impl_stimes_2(Process *c_p, Eterm *regs)
{
    return stimes_2(c_p, regs, (UWord *) bif_export[BIF_stimes_2]);
}

Eterm nbif_impl_div_2(Process *c_p, Eterm *regs)
{
    return div_2(c_p, regs, (UWord *) bif_export[BIF_div_2]);
}

Eterm nbif_impl_intdiv_2(Process *c_p, Eterm *regs)
{
    return intdiv_2(c_p, regs, (UWord *) bif_export[BIF_intdiv_2]);
}

Eterm nbif_impl_rem_2(Process *c_p, Eterm *regs)
{
    return rem_2(c_p, regs, (UWord *) bif_export[BIF_rem_2]);
}

Eterm nbif_impl_bor_2(Process *c_p, Eterm *regs)
{
    return bor_2(c_p, regs, (UWord *) bif_export[BIF_bor_2]);
}

Eterm nbif_impl_band_2(Process *c_p, Eterm *regs)
{
    return band_2(c_p, regs, (UWord *) bif_export[BIF_band_2]);
}

Eterm nbif_impl_bxor_2(Process *c_p, Eterm *regs)
{
    return bxor_2(c_p, regs, (UWord *) bif_export[BIF_bxor_2]);
}

Eterm nbif_impl_bsl_2(Process *c_p, Eterm *regs)
{
    return bsl_2(c_p, regs, (UWord *) bif_export[BIF_bsl_2]);
}

Eterm nbif_impl_bsr_2(Process *c_p, Eterm *regs)
{
    return bsr_2(c_p, regs, (UWord *) bif_export[BIF_bsr_2]);
}

Eterm nbif_impl_bnot_1(Process *c_p, Eterm *regs)
{
    return bnot_1(c_p, regs, (UWord *) bif_export[BIF_bnot_1]);
}

Eterm nbif_impl_sminus_1(Process *c_p, Eterm *regs)
{
    return sminus_1(c_p, regs, (UWord *) bif_export[BIF_sminus_1]);
}

Eterm nbif_impl_splus_1(Process *c_p, Eterm *regs)
{
    return splus_1(c_p, regs, (UWord *) bif_export[BIF_splus_1]);
}

Eterm nbif_impl_ebif_bang_2(Process *c_p, Eterm *regs)
{
    return ebif_bang_2(c_p, regs, (UWord *) bif_export[BIF_ebif_bang_2]);
}

Eterm nbif_impl_send_2(Process *c_p, Eterm *regs)
{
    return send_2(c_p, regs, (UWord *) bif_export[BIF_send_2]);
}

Eterm nbif_impl_send_3(Process *c_p, Eterm *regs)
{
    return send_3(c_p, regs, (UWord *) bif_export[BIF_send_3]);
}

Eterm nbif_impl_ebif_plusplus_2(Process *c_p, Eterm *regs)
{
    return ebif_plusplus_2(c_p, regs, (UWord *) bif_export[BIF_ebif_plusplus_2]);
}

Eterm nbif_impl_append_2(Process *c_p, Eterm *regs)
{
    return append_2(c_p, regs, (UWord *) bif_export[BIF_append_2]);
}

Eterm nbif_impl_ebif_minusminus_2(Process *c_p, Eterm *regs)
{
    return ebif_minusminus_2(c_p, regs, (UWord *) bif_export[BIF_ebif_minusminus_2]);
}

Eterm nbif_impl_subtract_2(Process *c_p, Eterm *regs)
{
    return subtract_2(c_p, regs, (UWord *) bif_export[BIF_subtract_2]);
}

Eterm nbif_impl_is_atom_1(Process *c_p, Eterm *regs)
{
    return is_atom_1(c_p, regs, (UWord *) bif_export[BIF_is_atom_1]);
}

Eterm nbif_impl_is_list_1(Process *c_p, Eterm *regs)
{
    return is_list_1(c_p, regs, (UWord *) bif_export[BIF_is_list_1]);
}

Eterm nbif_impl_is_tuple_1(Process *c_p, Eterm *regs)
{
    return is_tuple_1(c_p, regs, (UWord *) bif_export[BIF_is_tuple_1]);
}

Eterm nbif_impl_is_float_1(Process *c_p, Eterm *regs)
{
    return is_float_1(c_p, regs, (UWord *) bif_export[BIF_is_float_1]);
}

Eterm nbif_impl_is_integer_1(Process *c_p, Eterm *regs)
{
    return is_integer_1(c_p, regs, (UWord *) bif_export[BIF_is_integer_1]);
}

Eterm nbif_impl_is_number_1(Process *c_p, Eterm *regs)
{
    return is_number_1(c_p, regs, (UWord *) bif_export[BIF_is_number_1]);
}

Eterm nbif_impl_is_pid_1(Process *c_p, Eterm *regs)
{
    return is_pid_1(c_p, regs, (UWord *) bif_export[BIF_is_pid_1]);
}

Eterm nbif_impl_is_port_1(Process *c_p, Eterm *regs)
{
    return is_port_1(c_p, regs, (UWord *) bif_export[BIF_is_port_1]);
}

Eterm nbif_impl_is_reference_1(Process *c_p, Eterm *regs)
{
    return is_reference_1(c_p, regs, (UWord *) bif_export[BIF_is_reference_1]);
}

Eterm nbif_impl_is_binary_1(Process *c_p, Eterm *regs)
{
    return is_binary_1(c_p, regs, (UWord *) bif_export[BIF_is_binary_1]);
}

Eterm nbif_impl_is_function_1(Process *c_p, Eterm *regs)
{
    return is_function_1(c_p, regs, (UWord *) bif_export[BIF_is_function_1]);
}

Eterm nbif_impl_is_function_2(Process *c_p, Eterm *regs)
{
    return is_function_2(c_p, regs, (UWord *) bif_export[BIF_is_function_2]);
}

Eterm nbif_impl_is_record_2(Process *c_p, Eterm *regs)
{
    return is_record_2(c_p, regs, (UWord *) bif_export[BIF_is_record_2]);
}

Eterm nbif_impl_is_record_3(Process *c_p, Eterm *regs)
{
    return is_record_3(c_p, regs, (UWord *) bif_export[BIF_is_record_3]);
}

Eterm nbif_impl_match_spec_test_3(Process *c_p, Eterm *regs)
{
    return match_spec_test_3(c_p, regs, (UWord *) bif_export[BIF_match_spec_test_3]);
}

Eterm nbif_impl_ets_internal_request_all_0(Process *c_p, Eterm *regs)
{
    return ets_internal_request_all_0(c_p, regs, (UWord *) bif_export[BIF_ets_internal_request_all_0]);
}

Eterm nbif_impl_ets_new_2(Process *c_p, Eterm *regs)
{
    return ets_new_2(c_p, regs, (UWord *) bif_export[BIF_ets_new_2]);
}

Eterm nbif_impl_ets_delete_1(Process *c_p, Eterm *regs)
{
    return ets_delete_1(c_p, regs, (UWord *) bif_export[BIF_ets_delete_1]);
}

Eterm nbif_impl_ets_delete_2(Process *c_p, Eterm *regs)
{
    return ets_delete_2(c_p, regs, (UWord *) bif_export[BIF_ets_delete_2]);
}

Eterm nbif_impl_ets_delete_object_2(Process *c_p, Eterm *regs)
{
    return ets_delete_object_2(c_p, regs, (UWord *) bif_export[BIF_ets_delete_object_2]);
}

Eterm nbif_impl_ets_first_1(Process *c_p, Eterm *regs)
{
    return ets_first_1(c_p, regs, (UWord *) bif_export[BIF_ets_first_1]);
}

Eterm nbif_impl_ets_is_compiled_ms_1(Process *c_p, Eterm *regs)
{
    return ets_is_compiled_ms_1(c_p, regs, (UWord *) bif_export[BIF_ets_is_compiled_ms_1]);
}

Eterm nbif_impl_ets_lookup_2(Process *c_p, Eterm *regs)
{
    return ets_lookup_2(c_p, regs, (UWord *) bif_export[BIF_ets_lookup_2]);
}

Eterm nbif_impl_ets_lookup_element_3(Process *c_p, Eterm *regs)
{
    return ets_lookup_element_3(c_p, regs, (UWord *) bif_export[BIF_ets_lookup_element_3]);
}

Eterm nbif_impl_ets_info_1(Process *c_p, Eterm *regs)
{
    return ets_info_1(c_p, regs, (UWord *) bif_export[BIF_ets_info_1]);
}

Eterm nbif_impl_ets_info_2(Process *c_p, Eterm *regs)
{
    return ets_info_2(c_p, regs, (UWord *) bif_export[BIF_ets_info_2]);
}

Eterm nbif_impl_ets_last_1(Process *c_p, Eterm *regs)
{
    return ets_last_1(c_p, regs, (UWord *) bif_export[BIF_ets_last_1]);
}

Eterm nbif_impl_ets_match_1(Process *c_p, Eterm *regs)
{
    return ets_match_1(c_p, regs, (UWord *) bif_export[BIF_ets_match_1]);
}

Eterm nbif_impl_ets_match_2(Process *c_p, Eterm *regs)
{
    return ets_match_2(c_p, regs, (UWord *) bif_export[BIF_ets_match_2]);
}

Eterm nbif_impl_ets_match_3(Process *c_p, Eterm *regs)
{
    return ets_match_3(c_p, regs, (UWord *) bif_export[BIF_ets_match_3]);
}

Eterm nbif_impl_ets_match_object_1(Process *c_p, Eterm *regs)
{
    return ets_match_object_1(c_p, regs, (UWord *) bif_export[BIF_ets_match_object_1]);
}

Eterm nbif_impl_ets_match_object_2(Process *c_p, Eterm *regs)
{
    return ets_match_object_2(c_p, regs, (UWord *) bif_export[BIF_ets_match_object_2]);
}

Eterm nbif_impl_ets_match_object_3(Process *c_p, Eterm *regs)
{
    return ets_match_object_3(c_p, regs, (UWord *) bif_export[BIF_ets_match_object_3]);
}

Eterm nbif_impl_ets_member_2(Process *c_p, Eterm *regs)
{
    return ets_member_2(c_p, regs, (UWord *) bif_export[BIF_ets_member_2]);
}

Eterm nbif_impl_ets_next_2(Process *c_p, Eterm *regs)
{
    return ets_next_2(c_p, regs, (UWord *) bif_export[BIF_ets_next_2]);
}

Eterm nbif_impl_ets_prev_2(Process *c_p, Eterm *regs)
{
    return ets_prev_2(c_p, regs, (UWord *) bif_export[BIF_ets_prev_2]);
}

Eterm nbif_impl_ets_insert_2(Process *c_p, Eterm *regs)
{
    return ets_insert_2(c_p, regs, (UWord *) bif_export[BIF_ets_insert_2]);
}

Eterm nbif_impl_ets_insert_new_2(Process *c_p, Eterm *regs)
{
    return ets_insert_new_2(c_p, regs, (UWord *) bif_export[BIF_ets_insert_new_2]);
}

Eterm nbif_impl_ets_rename_2(Process *c_p, Eterm *regs)
{
    return ets_rename_2(c_p, regs, (UWord *) bif_export[BIF_ets_rename_2]);
}

Eterm nbif_impl_ets_safe_fixtable_2(Process *c_p, Eterm *regs)
{
    return ets_safe_fixtable_2(c_p, regs, (UWord *) bif_export[BIF_ets_safe_fixtable_2]);
}

Eterm nbif_impl_ets_slot_2(Process *c_p, Eterm *regs)
{
    return ets_slot_2(c_p, regs, (UWord *) bif_export[BIF_ets_slot_2]);
}

Eterm nbif_impl_ets_update_counter_3(Process *c_p, Eterm *regs)
{
    return ets_update_counter_3(c_p, regs, (UWord *) bif_export[BIF_ets_update_counter_3]);
}

Eterm nbif_impl_ets_select_1(Process *c_p, Eterm *regs)
{
    return ets_select_1(c_p, regs, (UWord *) bif_export[BIF_ets_select_1]);
}

Eterm nbif_impl_ets_select_2(Process *c_p, Eterm *regs)
{
    return ets_select_2(c_p, regs, (UWord *) bif_export[BIF_ets_select_2]);
}

Eterm nbif_impl_ets_select_3(Process *c_p, Eterm *regs)
{
    return ets_select_3(c_p, regs, (UWord *) bif_export[BIF_ets_select_3]);
}

Eterm nbif_impl_ets_select_count_2(Process *c_p, Eterm *regs)
{
    return ets_select_count_2(c_p, regs, (UWord *) bif_export[BIF_ets_select_count_2]);
}

Eterm nbif_impl_ets_select_reverse_1(Process *c_p, Eterm *regs)
{
    return ets_select_reverse_1(c_p, regs, (UWord *) bif_export[BIF_ets_select_reverse_1]);
}

Eterm nbif_impl_ets_select_reverse_2(Process *c_p, Eterm *regs)
{
    return ets_select_reverse_2(c_p, regs, (UWord *) bif_export[BIF_ets_select_reverse_2]);
}

Eterm nbif_impl_ets_select_reverse_3(Process *c_p, Eterm *regs)
{
    return ets_select_reverse_3(c_p, regs, (UWord *) bif_export[BIF_ets_select_reverse_3]);
}

Eterm nbif_impl_ets_select_replace_2(Process *c_p, Eterm *regs)
{
    return ets_select_replace_2(c_p, regs, (UWord *) bif_export[BIF_ets_select_replace_2]);
}

Eterm nbif_impl_ets_match_spec_compile_1(Process *c_p, Eterm *regs)
{
    return ets_match_spec_compile_1(c_p, regs, (UWord *) bif_export[BIF_ets_match_spec_compile_1]);
}

Eterm nbif_impl_ets_match_spec_run_r_3(Process *c_p, Eterm *regs)
{
    return ets_match_spec_run_r_3(c_p, regs, (UWord *) bif_export[BIF_ets_match_spec_run_r_3]);
}

Eterm nbif_impl_os_get_env_var_1(Process *c_p, Eterm *regs)
{
    return os_get_env_var_1(c_p, regs, (UWord *) bif_export[BIF_os_get_env_var_1]);
}

Eterm nbif_impl_os_set_env_var_2(Process *c_p, Eterm *regs)
{
    return os_set_env_var_2(c_p, regs, (UWord *) bif_export[BIF_os_set_env_var_2]);
}

Eterm nbif_impl_os_unset_env_var_1(Process *c_p, Eterm *regs)
{
    return os_unset_env_var_1(c_p, regs, (UWord *) bif_export[BIF_os_unset_env_var_1]);
}

Eterm nbif_impl_os_list_env_vars_0(Process *c_p, Eterm *regs)
{
    return os_list_env_vars_0(c_p, regs, (UWord *) bif_export[BIF_os_list_env_vars_0]);
}

Eterm nbif_impl_os_getpid_0(Process *c_p, Eterm *regs)
{
    return os_getpid_0(c_p, regs, (UWord *) bif_export[BIF_os_getpid_0]);
}

Eterm nbif_impl_os_timestamp_0(Process *c_p, Eterm *regs)
{
    return os_timestamp_0(c_p, regs, (UWord *) bif_export[BIF_os_timestamp_0]);
}

Eterm nbif_impl_os_system_time_0(Process *c_p, Eterm *regs)
{
    return os_system_time_0(c_p, regs, (UWord *) bif_export[BIF_os_system_time_0]);
}

Eterm nbif_impl_os_system_time_1(Process *c_p, Eterm *regs)
{
    return os_system_time_1(c_p, regs, (UWord *) bif_export[BIF_os_system_time_1]);
}

Eterm nbif_impl_os_perf_counter_0(Process *c_p, Eterm *regs)
{
    return os_perf_counter_0(c_p, regs, (UWord *) bif_export[BIF_os_perf_counter_0]);
}

Eterm nbif_impl_erl_ddll_try_load_3(Process *c_p, Eterm *regs)
{
    return erl_ddll_try_load_3(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_try_load_3]);
}

Eterm nbif_impl_erl_ddll_try_unload_2(Process *c_p, Eterm *regs)
{
    return erl_ddll_try_unload_2(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_try_unload_2]);
}

Eterm nbif_impl_erl_ddll_loaded_drivers_0(Process *c_p, Eterm *regs)
{
    return erl_ddll_loaded_drivers_0(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_loaded_drivers_0]);
}

Eterm nbif_impl_erl_ddll_info_2(Process *c_p, Eterm *regs)
{
    return erl_ddll_info_2(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_info_2]);
}

Eterm nbif_impl_erl_ddll_format_error_int_1(Process *c_p, Eterm *regs)
{
    return erl_ddll_format_error_int_1(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_format_error_int_1]);
}

Eterm nbif_impl_erl_ddll_monitor_2(Process *c_p, Eterm *regs)
{
    return erl_ddll_monitor_2(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_monitor_2]);
}

Eterm nbif_impl_erl_ddll_demonitor_1(Process *c_p, Eterm *regs)
{
    return erl_ddll_demonitor_1(c_p, regs, (UWord *) bif_export[BIF_erl_ddll_demonitor_1]);
}

Eterm nbif_impl_re_version_0(Process *c_p, Eterm *regs)
{
    return re_version_0(c_p, regs, (UWord *) bif_export[BIF_re_version_0]);
}

Eterm nbif_impl_re_compile_1(Process *c_p, Eterm *regs)
{
    return re_compile_1(c_p, regs, (UWord *) bif_export[BIF_re_compile_1]);
}

Eterm nbif_impl_re_compile_2(Process *c_p, Eterm *regs)
{
    return re_compile_2(c_p, regs, (UWord *) bif_export[BIF_re_compile_2]);
}

Eterm nbif_impl_re_run_2(Process *c_p, Eterm *regs)
{
    return re_run_2(c_p, regs, (UWord *) bif_export[BIF_re_run_2]);
}

Eterm nbif_impl_re_run_3(Process *c_p, Eterm *regs)
{
    return re_run_3(c_p, regs, (UWord *) bif_export[BIF_re_run_3]);
}

Eterm nbif_impl_re_internal_run_4(Process *c_p, Eterm *regs)
{
    return re_internal_run_4(c_p, regs, (UWord *) bif_export[BIF_re_internal_run_4]);
}

Eterm nbif_impl_lists_member_2(Process *c_p, Eterm *regs)
{
    return lists_member_2(c_p, regs, (UWord *) bif_export[BIF_lists_member_2]);
}

Eterm nbif_impl_lists_reverse_2(Process *c_p, Eterm *regs)
{
    return lists_reverse_2(c_p, regs, (UWord *) bif_export[BIF_lists_reverse_2]);
}

Eterm nbif_impl_lists_keymember_3(Process *c_p, Eterm *regs)
{
    return lists_keymember_3(c_p, regs, (UWord *) bif_export[BIF_lists_keymember_3]);
}

Eterm nbif_impl_lists_keysearch_3(Process *c_p, Eterm *regs)
{
    return lists_keysearch_3(c_p, regs, (UWord *) bif_export[BIF_lists_keysearch_3]);
}

Eterm nbif_impl_lists_keyfind_3(Process *c_p, Eterm *regs)
{
    return lists_keyfind_3(c_p, regs, (UWord *) bif_export[BIF_lists_keyfind_3]);
}

Eterm nbif_impl_erts_debug_disassemble_1(Process *c_p, Eterm *regs)
{
    return erts_debug_disassemble_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_disassemble_1]);
}

Eterm nbif_impl_erts_debug_breakpoint_2(Process *c_p, Eterm *regs)
{
    return erts_debug_breakpoint_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_breakpoint_2]);
}

Eterm nbif_impl_erts_debug_same_2(Process *c_p, Eterm *regs)
{
    return erts_debug_same_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_same_2]);
}

Eterm nbif_impl_erts_debug_flat_size_1(Process *c_p, Eterm *regs)
{
    return erts_debug_flat_size_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_flat_size_1]);
}

Eterm nbif_impl_erts_debug_get_internal_state_1(Process *c_p, Eterm *regs)
{
    return erts_debug_get_internal_state_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_get_internal_state_1]);
}

Eterm nbif_impl_erts_debug_set_internal_state_2(Process *c_p, Eterm *regs)
{
    return erts_debug_set_internal_state_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_set_internal_state_2]);
}

Eterm nbif_impl_erts_debug_display_1(Process *c_p, Eterm *regs)
{
    return erts_debug_display_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_display_1]);
}

Eterm nbif_impl_erts_debug_dist_ext_to_term_2(Process *c_p, Eterm *regs)
{
    return erts_debug_dist_ext_to_term_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_dist_ext_to_term_2]);
}

Eterm nbif_impl_erts_debug_instructions_0(Process *c_p, Eterm *regs)
{
    return erts_debug_instructions_0(c_p, regs, (UWord *) bif_export[BIF_erts_debug_instructions_0]);
}

Eterm nbif_impl_erts_debug_interpreter_size_0(Process *c_p, Eterm *regs)
{
    return erts_debug_interpreter_size_0(c_p, regs, (UWord *) bif_export[BIF_erts_debug_interpreter_size_0]);
}

Eterm nbif_impl_erts_debug_dirty_cpu_2(Process *c_p, Eterm *regs)
{
    return schedule_dirty_cpu_erts_debug_dirty_cpu_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_dirty_cpu_2]);
}

Eterm nbif_impl_erts_debug_dirty_io_2(Process *c_p, Eterm *regs)
{
    return schedule_dirty_io_erts_debug_dirty_io_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_dirty_io_2]);
}

Eterm nbif_impl_erts_debug_dirty_3(Process *c_p, Eterm *regs)
{
    return erts_debug_dirty_3(c_p, regs, (UWord *) bif_export[BIF_erts_debug_dirty_3]);
}

Eterm nbif_impl_erts_debug_lcnt_control_2(Process *c_p, Eterm *regs)
{
    return schedule_dirty_cpu_erts_debug_lcnt_control_2(c_p, regs, (UWord *) bif_export[BIF_erts_debug_lcnt_control_2]);
}

Eterm nbif_impl_erts_debug_lcnt_control_1(Process *c_p, Eterm *regs)
{
    return erts_debug_lcnt_control_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_lcnt_control_1]);
}

Eterm nbif_impl_erts_debug_lcnt_collect_0(Process *c_p, Eterm *regs)
{
    return schedule_dirty_cpu_erts_debug_lcnt_collect_0(c_p, regs, (UWord *) bif_export[BIF_erts_debug_lcnt_collect_0]);
}

Eterm nbif_impl_erts_debug_lcnt_clear_0(Process *c_p, Eterm *regs)
{
    return schedule_dirty_cpu_erts_debug_lcnt_clear_0(c_p, regs, (UWord *) bif_export[BIF_erts_debug_lcnt_clear_0]);
}

Eterm nbif_impl_code_get_chunk_2(Process *c_p, Eterm *regs)
{
    return code_get_chunk_2(c_p, regs, (UWord *) bif_export[BIF_code_get_chunk_2]);
}

Eterm nbif_impl_code_module_md5_1(Process *c_p, Eterm *regs)
{
    return code_module_md5_1(c_p, regs, (UWord *) bif_export[BIF_code_module_md5_1]);
}

Eterm nbif_impl_code_make_stub_module_3(Process *c_p, Eterm *regs)
{
    return code_make_stub_module_3(c_p, regs, (UWord *) bif_export[BIF_code_make_stub_module_3]);
}

Eterm nbif_impl_code_is_module_native_1(Process *c_p, Eterm *regs)
{
    return code_is_module_native_1(c_p, regs, (UWord *) bif_export[BIF_code_is_module_native_1]);
}

Eterm nbif_impl_hibernate_3(Process *c_p, Eterm *regs)
{
    return hibernate_3(c_p, regs, (UWord *) bif_export[BIF_hibernate_3]);
}

Eterm nbif_impl_error_logger_warning_map_0(Process *c_p, Eterm *regs)
{
    return error_logger_warning_map_0(c_p, regs, (UWord *) bif_export[BIF_error_logger_warning_map_0]);
}

Eterm nbif_impl_get_module_info_1(Process *c_p, Eterm *regs)
{
    return get_module_info_1(c_p, regs, (UWord *) bif_export[BIF_get_module_info_1]);
}

Eterm nbif_impl_get_module_info_2(Process *c_p, Eterm *regs)
{
    return get_module_info_2(c_p, regs, (UWord *) bif_export[BIF_get_module_info_2]);
}

Eterm nbif_impl_is_boolean_1(Process *c_p, Eterm *regs)
{
    return is_boolean_1(c_p, regs, (UWord *) bif_export[BIF_is_boolean_1]);
}

Eterm nbif_impl_string_list_to_integer_1(Process *c_p, Eterm *regs)
{
    return string_list_to_integer_1(c_p, regs, (UWord *) bif_export[BIF_string_list_to_integer_1]);
}

Eterm nbif_impl_string_list_to_float_1(Process *c_p, Eterm *regs)
{
    return string_list_to_float_1(c_p, regs, (UWord *) bif_export[BIF_string_list_to_float_1]);
}

Eterm nbif_impl_make_fun_3(Process *c_p, Eterm *regs)
{
    return make_fun_3(c_p, regs, (UWord *) bif_export[BIF_make_fun_3]);
}

Eterm nbif_impl_iolist_size_1(Process *c_p, Eterm *regs)
{
    return iolist_size_1(c_p, regs, (UWord *) bif_export[BIF_iolist_size_1]);
}

Eterm nbif_impl_iolist_to_binary_1(Process *c_p, Eterm *regs)
{
    return iolist_to_binary_1(c_p, regs, (UWord *) bif_export[BIF_iolist_to_binary_1]);
}

Eterm nbif_impl_list_to_existing_atom_1(Process *c_p, Eterm *regs)
{
    return list_to_existing_atom_1(c_p, regs, (UWord *) bif_export[BIF_list_to_existing_atom_1]);
}

Eterm nbif_impl_is_bitstring_1(Process *c_p, Eterm *regs)
{
    return is_bitstring_1(c_p, regs, (UWord *) bif_export[BIF_is_bitstring_1]);
}

Eterm nbif_impl_tuple_size_1(Process *c_p, Eterm *regs)
{
    return tuple_size_1(c_p, regs, (UWord *) bif_export[BIF_tuple_size_1]);
}

Eterm nbif_impl_byte_size_1(Process *c_p, Eterm *regs)
{
    return byte_size_1(c_p, regs, (UWord *) bif_export[BIF_byte_size_1]);
}

Eterm nbif_impl_bit_size_1(Process *c_p, Eterm *regs)
{
    return bit_size_1(c_p, regs, (UWord *) bif_export[BIF_bit_size_1]);
}

Eterm nbif_impl_list_to_bitstring_1(Process *c_p, Eterm *regs)
{
    return list_to_bitstring_1(c_p, regs, (UWord *) bif_export[BIF_list_to_bitstring_1]);
}

Eterm nbif_impl_bitstring_to_list_1(Process *c_p, Eterm *regs)
{
    return bitstring_to_list_1(c_p, regs, (UWord *) bif_export[BIF_bitstring_to_list_1]);
}

Eterm nbif_impl_ets_update_element_3(Process *c_p, Eterm *regs)
{
    return ets_update_element_3(c_p, regs, (UWord *) bif_export[BIF_ets_update_element_3]);
}

Eterm nbif_impl_decode_packet_3(Process *c_p, Eterm *regs)
{
    return decode_packet_3(c_p, regs, (UWord *) bif_export[BIF_decode_packet_3]);
}

Eterm nbif_impl_unicode_characters_to_binary_2(Process *c_p, Eterm *regs)
{
    return unicode_characters_to_binary_2(c_p, regs, (UWord *) bif_export[BIF_unicode_characters_to_binary_2]);
}

Eterm nbif_impl_unicode_characters_to_list_2(Process *c_p, Eterm *regs)
{
    return unicode_characters_to_list_2(c_p, regs, (UWord *) bif_export[BIF_unicode_characters_to_list_2]);
}

Eterm nbif_impl_unicode_bin_is_7bit_1(Process *c_p, Eterm *regs)
{
    return unicode_bin_is_7bit_1(c_p, regs, (UWord *) bif_export[BIF_unicode_bin_is_7bit_1]);
}

Eterm nbif_impl_atom_to_binary_2(Process *c_p, Eterm *regs)
{
    return atom_to_binary_2(c_p, regs, (UWord *) bif_export[BIF_atom_to_binary_2]);
}

Eterm nbif_impl_binary_to_atom_2(Process *c_p, Eterm *regs)
{
    return binary_to_atom_2(c_p, regs, (UWord *) bif_export[BIF_binary_to_atom_2]);
}

Eterm nbif_impl_binary_to_existing_atom_2(Process *c_p, Eterm *regs)
{
    return binary_to_existing_atom_2(c_p, regs, (UWord *) bif_export[BIF_binary_to_existing_atom_2]);
}

Eterm nbif_impl_net_kernel_dflag_unicode_io_1(Process *c_p, Eterm *regs)
{
    return net_kernel_dflag_unicode_io_1(c_p, regs, (UWord *) bif_export[BIF_net_kernel_dflag_unicode_io_1]);
}

Eterm nbif_impl_ets_give_away_3(Process *c_p, Eterm *regs)
{
    return ets_give_away_3(c_p, regs, (UWord *) bif_export[BIF_ets_give_away_3]);
}

Eterm nbif_impl_ets_setopts_2(Process *c_p, Eterm *regs)
{
    return ets_setopts_2(c_p, regs, (UWord *) bif_export[BIF_ets_setopts_2]);
}

Eterm nbif_impl_load_nif_2(Process *c_p, Eterm *regs)
{
    return load_nif_2(c_p, regs, (UWord *) bif_export[BIF_load_nif_2]);
}

Eterm nbif_impl_call_on_load_function_1(Process *c_p, Eterm *regs)
{
    return call_on_load_function_1(c_p, regs, (UWord *) bif_export[BIF_call_on_load_function_1]);
}

Eterm nbif_impl_finish_after_on_load_2(Process *c_p, Eterm *regs)
{
    return finish_after_on_load_2(c_p, regs, (UWord *) bif_export[BIF_finish_after_on_load_2]);
}

Eterm nbif_impl_binary_to_term_2(Process *c_p, Eterm *regs)
{
    return binary_to_term_2(c_p, regs, (UWord *) bif_export[BIF_binary_to_term_2]);
}

Eterm nbif_impl_binary_part_2(Process *c_p, Eterm *regs)
{
    return binary_part_2(c_p, regs, (UWord *) bif_export[BIF_binary_part_2]);
}

Eterm nbif_impl_binary_part_3(Process *c_p, Eterm *regs)
{
    return binary_part_3(c_p, regs, (UWord *) bif_export[BIF_binary_part_3]);
}

Eterm nbif_impl_binary_compile_pattern_1(Process *c_p, Eterm *regs)
{
    return binary_compile_pattern_1(c_p, regs, (UWord *) bif_export[BIF_binary_compile_pattern_1]);
}

Eterm nbif_impl_binary_match_2(Process *c_p, Eterm *regs)
{
    return binary_match_2(c_p, regs, (UWord *) bif_export[BIF_binary_match_2]);
}

Eterm nbif_impl_binary_match_3(Process *c_p, Eterm *regs)
{
    return binary_match_3(c_p, regs, (UWord *) bif_export[BIF_binary_match_3]);
}

Eterm nbif_impl_binary_matches_2(Process *c_p, Eterm *regs)
{
    return binary_matches_2(c_p, regs, (UWord *) bif_export[BIF_binary_matches_2]);
}

Eterm nbif_impl_binary_matches_3(Process *c_p, Eterm *regs)
{
    return binary_matches_3(c_p, regs, (UWord *) bif_export[BIF_binary_matches_3]);
}

Eterm nbif_impl_binary_longest_common_prefix_1(Process *c_p, Eterm *regs)
{
    return binary_longest_common_prefix_1(c_p, regs, (UWord *) bif_export[BIF_binary_longest_common_prefix_1]);
}

Eterm nbif_impl_binary_longest_common_suffix_1(Process *c_p, Eterm *regs)
{
    return binary_longest_common_suffix_1(c_p, regs, (UWord *) bif_export[BIF_binary_longest_common_suffix_1]);
}

Eterm nbif_impl_binary_first_1(Process *c_p, Eterm *regs)
{
    return binary_first_1(c_p, regs, (UWord *) bif_export[BIF_binary_first_1]);
}

Eterm nbif_impl_binary_last_1(Process *c_p, Eterm *regs)
{
    return binary_last_1(c_p, regs, (UWord *) bif_export[BIF_binary_last_1]);
}

Eterm nbif_impl_binary_at_2(Process *c_p, Eterm *regs)
{
    return binary_at_2(c_p, regs, (UWord *) bif_export[BIF_binary_at_2]);
}

Eterm nbif_impl_binary_binary_part_2(Process *c_p, Eterm *regs)
{
    return binary_binary_part_2(c_p, regs, (UWord *) bif_export[BIF_binary_binary_part_2]);
}

Eterm nbif_impl_binary_binary_part_3(Process *c_p, Eterm *regs)
{
    return binary_binary_part_3(c_p, regs, (UWord *) bif_export[BIF_binary_binary_part_3]);
}

Eterm nbif_impl_binary_list_to_bin_1(Process *c_p, Eterm *regs)
{
    return binary_list_to_bin_1(c_p, regs, (UWord *) bif_export[BIF_binary_list_to_bin_1]);
}

Eterm nbif_impl_binary_copy_1(Process *c_p, Eterm *regs)
{
    return binary_copy_1(c_p, regs, (UWord *) bif_export[BIF_binary_copy_1]);
}

Eterm nbif_impl_binary_copy_2(Process *c_p, Eterm *regs)
{
    return binary_copy_2(c_p, regs, (UWord *) bif_export[BIF_binary_copy_2]);
}

Eterm nbif_impl_binary_referenced_byte_size_1(Process *c_p, Eterm *regs)
{
    return binary_referenced_byte_size_1(c_p, regs, (UWord *) bif_export[BIF_binary_referenced_byte_size_1]);
}

Eterm nbif_impl_binary_encode_unsigned_1(Process *c_p, Eterm *regs)
{
    return binary_encode_unsigned_1(c_p, regs, (UWord *) bif_export[BIF_binary_encode_unsigned_1]);
}

Eterm nbif_impl_binary_encode_unsigned_2(Process *c_p, Eterm *regs)
{
    return binary_encode_unsigned_2(c_p, regs, (UWord *) bif_export[BIF_binary_encode_unsigned_2]);
}

Eterm nbif_impl_binary_decode_unsigned_1(Process *c_p, Eterm *regs)
{
    return binary_decode_unsigned_1(c_p, regs, (UWord *) bif_export[BIF_binary_decode_unsigned_1]);
}

Eterm nbif_impl_binary_decode_unsigned_2(Process *c_p, Eterm *regs)
{
    return binary_decode_unsigned_2(c_p, regs, (UWord *) bif_export[BIF_binary_decode_unsigned_2]);
}

Eterm nbif_impl_nif_error_1(Process *c_p, Eterm *regs)
{
    return nif_error_1(c_p, regs, (UWord *) bif_export[BIF_nif_error_1]);
}

Eterm nbif_impl_nif_error_2(Process *c_p, Eterm *regs)
{
    return nif_error_2(c_p, regs, (UWord *) bif_export[BIF_nif_error_2]);
}

Eterm nbif_impl_prim_file_internal_name2native_1(Process *c_p, Eterm *regs)
{
    return prim_file_internal_name2native_1(c_p, regs, (UWord *) bif_export[BIF_prim_file_internal_name2native_1]);
}

Eterm nbif_impl_prim_file_internal_native2name_1(Process *c_p, Eterm *regs)
{
    return prim_file_internal_native2name_1(c_p, regs, (UWord *) bif_export[BIF_prim_file_internal_native2name_1]);
}

Eterm nbif_impl_prim_file_internal_normalize_utf8_1(Process *c_p, Eterm *regs)
{
    return prim_file_internal_normalize_utf8_1(c_p, regs, (UWord *) bif_export[BIF_prim_file_internal_normalize_utf8_1]);
}

Eterm nbif_impl_prim_file_is_translatable_1(Process *c_p, Eterm *regs)
{
    return prim_file_is_translatable_1(c_p, regs, (UWord *) bif_export[BIF_prim_file_is_translatable_1]);
}

Eterm nbif_impl_file_native_name_encoding_0(Process *c_p, Eterm *regs)
{
    return file_native_name_encoding_0(c_p, regs, (UWord *) bif_export[BIF_file_native_name_encoding_0]);
}

Eterm nbif_impl_check_old_code_1(Process *c_p, Eterm *regs)
{
    return check_old_code_1(c_p, regs, (UWord *) bif_export[BIF_check_old_code_1]);
}

Eterm nbif_impl_universaltime_to_posixtime_1(Process *c_p, Eterm *regs)
{
    return universaltime_to_posixtime_1(c_p, regs, (UWord *) bif_export[BIF_universaltime_to_posixtime_1]);
}

Eterm nbif_impl_posixtime_to_universaltime_1(Process *c_p, Eterm *regs)
{
    return posixtime_to_universaltime_1(c_p, regs, (UWord *) bif_export[BIF_posixtime_to_universaltime_1]);
}

Eterm nbif_impl_dt_put_tag_1(Process *c_p, Eterm *regs)
{
    return dt_put_tag_1(c_p, regs, (UWord *) bif_export[BIF_dt_put_tag_1]);
}

Eterm nbif_impl_dt_get_tag_0(Process *c_p, Eterm *regs)
{
    return dt_get_tag_0(c_p, regs, (UWord *) bif_export[BIF_dt_get_tag_0]);
}

Eterm nbif_impl_dt_get_tag_data_0(Process *c_p, Eterm *regs)
{
    return dt_get_tag_data_0(c_p, regs, (UWord *) bif_export[BIF_dt_get_tag_data_0]);
}

Eterm nbif_impl_dt_spread_tag_1(Process *c_p, Eterm *regs)
{
    return dt_spread_tag_1(c_p, regs, (UWord *) bif_export[BIF_dt_spread_tag_1]);
}

Eterm nbif_impl_dt_restore_tag_1(Process *c_p, Eterm *regs)
{
    return dt_restore_tag_1(c_p, regs, (UWord *) bif_export[BIF_dt_restore_tag_1]);
}

Eterm nbif_impl_dt_prepend_vm_tag_data_1(Process *c_p, Eterm *regs)
{
    return dt_prepend_vm_tag_data_1(c_p, regs, (UWord *) bif_export[BIF_dt_prepend_vm_tag_data_1]);
}

Eterm nbif_impl_dt_append_vm_tag_data_1(Process *c_p, Eterm *regs)
{
    return dt_append_vm_tag_data_1(c_p, regs, (UWord *) bif_export[BIF_dt_append_vm_tag_data_1]);
}

Eterm nbif_impl_prepare_loading_2(Process *c_p, Eterm *regs)
{
    return prepare_loading_2(c_p, regs, (UWord *) bif_export[BIF_prepare_loading_2]);
}

Eterm nbif_impl_finish_loading_1(Process *c_p, Eterm *regs)
{
    return finish_loading_1(c_p, regs, (UWord *) bif_export[BIF_finish_loading_1]);
}

Eterm nbif_impl_insert_element_3(Process *c_p, Eterm *regs)
{
    return insert_element_3(c_p, regs, (UWord *) bif_export[BIF_insert_element_3]);
}

Eterm nbif_impl_delete_element_2(Process *c_p, Eterm *regs)
{
    return delete_element_2(c_p, regs, (UWord *) bif_export[BIF_delete_element_2]);
}

Eterm nbif_impl_binary_to_integer_1(Process *c_p, Eterm *regs)
{
    return binary_to_integer_1(c_p, regs, (UWord *) bif_export[BIF_binary_to_integer_1]);
}

Eterm nbif_impl_binary_to_integer_2(Process *c_p, Eterm *regs)
{
    return binary_to_integer_2(c_p, regs, (UWord *) bif_export[BIF_binary_to_integer_2]);
}

Eterm nbif_impl_integer_to_binary_1(Process *c_p, Eterm *regs)
{
    return integer_to_binary_1(c_p, regs, (UWord *) bif_export[BIF_integer_to_binary_1]);
}

Eterm nbif_impl_list_to_integer_2(Process *c_p, Eterm *regs)
{
    return list_to_integer_2(c_p, regs, (UWord *) bif_export[BIF_list_to_integer_2]);
}

Eterm nbif_impl_float_to_binary_1(Process *c_p, Eterm *regs)
{
    return float_to_binary_1(c_p, regs, (UWord *) bif_export[BIF_float_to_binary_1]);
}

Eterm nbif_impl_float_to_binary_2(Process *c_p, Eterm *regs)
{
    return float_to_binary_2(c_p, regs, (UWord *) bif_export[BIF_float_to_binary_2]);
}

Eterm nbif_impl_binary_to_float_1(Process *c_p, Eterm *regs)
{
    return binary_to_float_1(c_p, regs, (UWord *) bif_export[BIF_binary_to_float_1]);
}

Eterm nbif_impl_io_printable_range_0(Process *c_p, Eterm *regs)
{
    return io_printable_range_0(c_p, regs, (UWord *) bif_export[BIF_io_printable_range_0]);
}

Eterm nbif_impl_re_inspect_2(Process *c_p, Eterm *regs)
{
    return re_inspect_2(c_p, regs, (UWord *) bif_export[BIF_re_inspect_2]);
}

Eterm nbif_impl_is_map_1(Process *c_p, Eterm *regs)
{
    return is_map_1(c_p, regs, (UWord *) bif_export[BIF_is_map_1]);
}

Eterm nbif_impl_map_size_1(Process *c_p, Eterm *regs)
{
    return map_size_1(c_p, regs, (UWord *) bif_export[BIF_map_size_1]);
}

Eterm nbif_impl_maps_find_2(Process *c_p, Eterm *regs)
{
    return maps_find_2(c_p, regs, (UWord *) bif_export[BIF_maps_find_2]);
}

Eterm nbif_impl_maps_get_2(Process *c_p, Eterm *regs)
{
    return maps_get_2(c_p, regs, (UWord *) bif_export[BIF_maps_get_2]);
}

Eterm nbif_impl_maps_from_list_1(Process *c_p, Eterm *regs)
{
    return maps_from_list_1(c_p, regs, (UWord *) bif_export[BIF_maps_from_list_1]);
}

Eterm nbif_impl_maps_is_key_2(Process *c_p, Eterm *regs)
{
    return maps_is_key_2(c_p, regs, (UWord *) bif_export[BIF_maps_is_key_2]);
}

Eterm nbif_impl_maps_keys_1(Process *c_p, Eterm *regs)
{
    return maps_keys_1(c_p, regs, (UWord *) bif_export[BIF_maps_keys_1]);
}

Eterm nbif_impl_maps_merge_2(Process *c_p, Eterm *regs)
{
    return maps_merge_2(c_p, regs, (UWord *) bif_export[BIF_maps_merge_2]);
}

Eterm nbif_impl_maps_put_3(Process *c_p, Eterm *regs)
{
    return maps_put_3(c_p, regs, (UWord *) bif_export[BIF_maps_put_3]);
}

Eterm nbif_impl_maps_remove_2(Process *c_p, Eterm *regs)
{
    return maps_remove_2(c_p, regs, (UWord *) bif_export[BIF_maps_remove_2]);
}

Eterm nbif_impl_maps_update_3(Process *c_p, Eterm *regs)
{
    return maps_update_3(c_p, regs, (UWord *) bif_export[BIF_maps_update_3]);
}

Eterm nbif_impl_maps_values_1(Process *c_p, Eterm *regs)
{
    return maps_values_1(c_p, regs, (UWord *) bif_export[BIF_maps_values_1]);
}

Eterm nbif_impl_erts_internal_cmp_term_2(Process *c_p, Eterm *regs)
{
    return erts_internal_cmp_term_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_cmp_term_2]);
}

Eterm nbif_impl_ets_take_2(Process *c_p, Eterm *regs)
{
    return ets_take_2(c_p, regs, (UWord *) bif_export[BIF_ets_take_2]);
}

Eterm nbif_impl_fun_info_mfa_1(Process *c_p, Eterm *regs)
{
    return fun_info_mfa_1(c_p, regs, (UWord *) bif_export[BIF_fun_info_mfa_1]);
}

Eterm nbif_impl_get_keys_0(Process *c_p, Eterm *regs)
{
    return get_keys_0(c_p, regs, (UWord *) bif_export[BIF_get_keys_0]);
}

Eterm nbif_impl_ets_update_counter_4(Process *c_p, Eterm *regs)
{
    return ets_update_counter_4(c_p, regs, (UWord *) bif_export[BIF_ets_update_counter_4]);
}

Eterm nbif_impl_erts_debug_map_info_1(Process *c_p, Eterm *regs)
{
    return erts_debug_map_info_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_map_info_1]);
}

Eterm nbif_impl_erts_internal_is_process_executing_dirty_1(Process *c_p, Eterm *regs)
{
    return erts_internal_is_process_executing_dirty_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_is_process_executing_dirty_1]);
}

Eterm nbif_impl_erts_internal_check_dirty_process_code_2(Process *c_p, Eterm *regs)
{
    return erts_internal_check_dirty_process_code_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_check_dirty_process_code_2]);
}

Eterm nbif_impl_erts_internal_purge_module_2(Process *c_p, Eterm *regs)
{
    return erts_internal_purge_module_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_purge_module_2]);
}

Eterm nbif_impl_binary_split_2(Process *c_p, Eterm *regs)
{
    return binary_split_2(c_p, regs, (UWord *) bif_export[BIF_binary_split_2]);
}

Eterm nbif_impl_binary_split_3(Process *c_p, Eterm *regs)
{
    return binary_split_3(c_p, regs, (UWord *) bif_export[BIF_binary_split_3]);
}

Eterm nbif_impl_erts_debug_size_shared_1(Process *c_p, Eterm *regs)
{
    return erts_debug_size_shared_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_size_shared_1]);
}

Eterm nbif_impl_erts_debug_copy_shared_1(Process *c_p, Eterm *regs)
{
    return erts_debug_copy_shared_1(c_p, regs, (UWord *) bif_export[BIF_erts_debug_copy_shared_1]);
}

Eterm nbif_impl_has_prepared_code_on_load_1(Process *c_p, Eterm *regs)
{
    return has_prepared_code_on_load_1(c_p, regs, (UWord *) bif_export[BIF_has_prepared_code_on_load_1]);
}

Eterm nbif_impl_maps_take_2(Process *c_p, Eterm *regs)
{
    return maps_take_2(c_p, regs, (UWord *) bif_export[BIF_maps_take_2]);
}

Eterm nbif_impl_floor_1(Process *c_p, Eterm *regs)
{
    return floor_1(c_p, regs, (UWord *) bif_export[BIF_floor_1]);
}

Eterm nbif_impl_ceil_1(Process *c_p, Eterm *regs)
{
    return ceil_1(c_p, regs, (UWord *) bif_export[BIF_ceil_1]);
}

Eterm nbif_impl_math_floor_1(Process *c_p, Eterm *regs)
{
    return math_floor_1(c_p, regs, (UWord *) bif_export[BIF_math_floor_1]);
}

Eterm nbif_impl_math_ceil_1(Process *c_p, Eterm *regs)
{
    return math_ceil_1(c_p, regs, (UWord *) bif_export[BIF_math_ceil_1]);
}

Eterm nbif_impl_math_fmod_2(Process *c_p, Eterm *regs)
{
    return math_fmod_2(c_p, regs, (UWord *) bif_export[BIF_math_fmod_2]);
}

Eterm nbif_impl_os_set_signal_2(Process *c_p, Eterm *regs)
{
    return os_set_signal_2(c_p, regs, (UWord *) bif_export[BIF_os_set_signal_2]);
}

Eterm nbif_impl_iolist_to_iovec_1(Process *c_p, Eterm *regs)
{
    return iolist_to_iovec_1(c_p, regs, (UWord *) bif_export[BIF_iolist_to_iovec_1]);
}

Eterm nbif_impl_erts_internal_get_dflags_0(Process *c_p, Eterm *regs)
{
    return erts_internal_get_dflags_0(c_p, regs, (UWord *) bif_export[BIF_erts_internal_get_dflags_0]);
}

Eterm nbif_impl_erts_internal_new_connection_1(Process *c_p, Eterm *regs)
{
    return erts_internal_new_connection_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_new_connection_1]);
}

Eterm nbif_impl_erts_internal_abort_connection_2(Process *c_p, Eterm *regs)
{
    return erts_internal_abort_connection_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_abort_connection_2]);
}

Eterm nbif_impl_erts_internal_map_next_3(Process *c_p, Eterm *regs)
{
    return erts_internal_map_next_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_map_next_3]);
}

Eterm nbif_impl_ets_whereis_1(Process *c_p, Eterm *regs)
{
    return ets_whereis_1(c_p, regs, (UWord *) bif_export[BIF_ets_whereis_1]);
}

Eterm nbif_impl_erts_internal_gather_alloc_histograms_1(Process *c_p, Eterm *regs)
{
    return erts_internal_gather_alloc_histograms_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_gather_alloc_histograms_1]);
}

Eterm nbif_impl_erts_internal_gather_carrier_info_1(Process *c_p, Eterm *regs)
{
    return erts_internal_gather_carrier_info_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_gather_carrier_info_1]);
}

Eterm nbif_impl_map_get_2(Process *c_p, Eterm *regs)
{
    return map_get_2(c_p, regs, (UWord *) bif_export[BIF_map_get_2]);
}

Eterm nbif_impl_is_map_key_2(Process *c_p, Eterm *regs)
{
    return is_map_key_2(c_p, regs, (UWord *) bif_export[BIF_is_map_key_2]);
}

Eterm nbif_impl_ets_internal_delete_all_2(Process *c_p, Eterm *regs)
{
    return ets_internal_delete_all_2(c_p, regs, (UWord *) bif_export[BIF_ets_internal_delete_all_2]);
}

Eterm nbif_impl_ets_internal_select_delete_2(Process *c_p, Eterm *regs)
{
    return ets_internal_select_delete_2(c_p, regs, (UWord *) bif_export[BIF_ets_internal_select_delete_2]);
}

Eterm nbif_impl_persistent_term_put_2(Process *c_p, Eterm *regs)
{
    return persistent_term_put_2(c_p, regs, (UWord *) bif_export[BIF_persistent_term_put_2]);
}

Eterm nbif_impl_persistent_term_get_1(Process *c_p, Eterm *regs)
{
    return persistent_term_get_1(c_p, regs, (UWord *) bif_export[BIF_persistent_term_get_1]);
}

Eterm nbif_impl_persistent_term_get_0(Process *c_p, Eterm *regs)
{
    return persistent_term_get_0(c_p, regs, (UWord *) bif_export[BIF_persistent_term_get_0]);
}

Eterm nbif_impl_persistent_term_erase_1(Process *c_p, Eterm *regs)
{
    return persistent_term_erase_1(c_p, regs, (UWord *) bif_export[BIF_persistent_term_erase_1]);
}

Eterm nbif_impl_persistent_term_info_0(Process *c_p, Eterm *regs)
{
    return persistent_term_info_0(c_p, regs, (UWord *) bif_export[BIF_persistent_term_info_0]);
}

Eterm nbif_impl_erts_internal_erase_persistent_terms_0(Process *c_p, Eterm *regs)
{
    return erts_internal_erase_persistent_terms_0(c_p, regs, (UWord *) bif_export[BIF_erts_internal_erase_persistent_terms_0]);
}

Eterm nbif_impl_erts_internal_atomics_new_2(Process *c_p, Eterm *regs)
{
    return erts_internal_atomics_new_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_atomics_new_2]);
}

Eterm nbif_impl_atomics_get_2(Process *c_p, Eterm *regs)
{
    return atomics_get_2(c_p, regs, (UWord *) bif_export[BIF_atomics_get_2]);
}

Eterm nbif_impl_atomics_put_3(Process *c_p, Eterm *regs)
{
    return atomics_put_3(c_p, regs, (UWord *) bif_export[BIF_atomics_put_3]);
}

Eterm nbif_impl_atomics_add_3(Process *c_p, Eterm *regs)
{
    return atomics_add_3(c_p, regs, (UWord *) bif_export[BIF_atomics_add_3]);
}

Eterm nbif_impl_atomics_add_get_3(Process *c_p, Eterm *regs)
{
    return atomics_add_get_3(c_p, regs, (UWord *) bif_export[BIF_atomics_add_get_3]);
}

Eterm nbif_impl_atomics_exchange_3(Process *c_p, Eterm *regs)
{
    return atomics_exchange_3(c_p, regs, (UWord *) bif_export[BIF_atomics_exchange_3]);
}

Eterm nbif_impl_atomics_compare_exchange_4(Process *c_p, Eterm *regs)
{
    return atomics_compare_exchange_4(c_p, regs, (UWord *) bif_export[BIF_atomics_compare_exchange_4]);
}

Eterm nbif_impl_atomics_info_1(Process *c_p, Eterm *regs)
{
    return atomics_info_1(c_p, regs, (UWord *) bif_export[BIF_atomics_info_1]);
}

Eterm nbif_impl_erts_internal_counters_new_1(Process *c_p, Eterm *regs)
{
    return erts_internal_counters_new_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_counters_new_1]);
}

Eterm nbif_impl_erts_internal_counters_get_2(Process *c_p, Eterm *regs)
{
    return erts_internal_counters_get_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_counters_get_2]);
}

Eterm nbif_impl_erts_internal_counters_add_3(Process *c_p, Eterm *regs)
{
    return erts_internal_counters_add_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_counters_add_3]);
}

Eterm nbif_impl_erts_internal_counters_put_3(Process *c_p, Eterm *regs)
{
    return erts_internal_counters_put_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_counters_put_3]);
}

Eterm nbif_impl_erts_internal_counters_info_1(Process *c_p, Eterm *regs)
{
    return erts_internal_counters_info_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_counters_info_1]);
}

Eterm nbif_impl_erts_internal_spawn_system_process_3(Process *c_p, Eterm *regs)
{
    return erts_internal_spawn_system_process_3(c_p, regs, (UWord *) bif_export[BIF_erts_internal_spawn_system_process_3]);
}

Eterm nbif_impl_integer_to_list_2(Process *c_p, Eterm *regs)
{
    return integer_to_list_2(c_p, regs, (UWord *) bif_export[BIF_integer_to_list_2]);
}

Eterm nbif_impl_integer_to_binary_2(Process *c_p, Eterm *regs)
{
    return integer_to_binary_2(c_p, regs, (UWord *) bif_export[BIF_integer_to_binary_2]);
}

Eterm nbif_impl_persistent_term_get_2(Process *c_p, Eterm *regs)
{
    return persistent_term_get_2(c_p, regs, (UWord *) bif_export[BIF_persistent_term_get_2]);
}

Eterm nbif_impl_erts_internal_ets_lookup_binary_info_2(Process *c_p, Eterm *regs)
{
    return erts_internal_ets_lookup_binary_info_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_ets_lookup_binary_info_2]);
}

Eterm nbif_impl_erts_internal_ets_raw_first_1(Process *c_p, Eterm *regs)
{
    return erts_internal_ets_raw_first_1(c_p, regs, (UWord *) bif_export[BIF_erts_internal_ets_raw_first_1]);
}

Eterm nbif_impl_erts_internal_ets_raw_next_2(Process *c_p, Eterm *regs)
{
    return erts_internal_ets_raw_next_2(c_p, regs, (UWord *) bif_export[BIF_erts_internal_ets_raw_next_2]);
}

Eterm nbif_impl_hipe_bifs_write_u8_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_write_u8_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_write_u8_2]);
}

Eterm nbif_impl_hipe_bifs_write_u32_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_write_u32_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_write_u32_2]);
}

Eterm nbif_impl_hipe_bifs_bytearray_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bytearray_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bytearray_2]);
}

Eterm nbif_impl_hipe_bifs_bytearray_sub_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bytearray_sub_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bytearray_sub_2]);
}

Eterm nbif_impl_hipe_bifs_bytearray_update_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bytearray_update_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bytearray_update_3]);
}

Eterm nbif_impl_hipe_bifs_bitarray_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bitarray_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bitarray_2]);
}

Eterm nbif_impl_hipe_bifs_bitarray_sub_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bitarray_sub_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bitarray_sub_2]);
}

Eterm nbif_impl_hipe_bifs_bitarray_update_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bitarray_update_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bitarray_update_3]);
}

Eterm nbif_impl_hipe_bifs_array_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_array_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_array_2]);
}

Eterm nbif_impl_hipe_bifs_array_length_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_array_length_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_array_length_1]);
}

Eterm nbif_impl_hipe_bifs_array_sub_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_array_sub_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_array_sub_2]);
}

Eterm nbif_impl_hipe_bifs_array_update_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_array_update_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_array_update_3]);
}

Eterm nbif_impl_hipe_bifs_ref_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_ref_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_ref_1]);
}

Eterm nbif_impl_hipe_bifs_ref_get_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_ref_get_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_ref_get_1]);
}

Eterm nbif_impl_hipe_bifs_ref_set_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_ref_set_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_ref_set_2]);
}

Eterm nbif_impl_hipe_bifs_enter_code_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_enter_code_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_enter_code_3]);
}

Eterm nbif_impl_hipe_bifs_alloc_data_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_alloc_data_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_alloc_data_3]);
}

Eterm nbif_impl_hipe_bifs_constants_size_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_constants_size_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_constants_size_0]);
}

Eterm nbif_impl_hipe_bifs_merge_term_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_merge_term_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_merge_term_1]);
}

Eterm nbif_impl_hipe_bifs_fun_to_address_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_fun_to_address_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_fun_to_address_1]);
}

Eterm nbif_impl_hipe_bifs_commit_patch_load_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_commit_patch_load_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_commit_patch_load_1]);
}

Eterm nbif_impl_hipe_bifs_set_native_address_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_set_native_address_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_set_native_address_3]);
}

Eterm nbif_impl_hipe_bifs_set_funinfo_native_address_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_set_funinfo_native_address_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_set_funinfo_native_address_3]);
}

Eterm nbif_impl_hipe_bifs_enter_sdesc_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_enter_sdesc_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_enter_sdesc_2]);
}

Eterm nbif_impl_hipe_bifs_bif_address_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_bif_address_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_bif_address_3]);
}

Eterm nbif_impl_hipe_bifs_primop_address_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_primop_address_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_primop_address_1]);
}

Eterm nbif_impl_hipe_bifs_atom_to_word_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_atom_to_word_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_atom_to_word_1]);
}

Eterm nbif_impl_hipe_bifs_term_to_word_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_term_to_word_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_term_to_word_1]);
}

Eterm nbif_impl_hipe_bifs_get_fe_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_get_fe_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_get_fe_2]);
}

Eterm nbif_impl_hipe_bifs_set_native_address_in_fe_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_set_native_address_in_fe_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_set_native_address_in_fe_2]);
}

Eterm nbif_impl_hipe_bifs_find_na_or_make_stub_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_find_na_or_make_stub_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_find_na_or_make_stub_1]);
}

Eterm nbif_impl_hipe_bifs_check_crc_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_check_crc_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_check_crc_1]);
}

Eterm nbif_impl_hipe_bifs_system_crc_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_system_crc_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_system_crc_0]);
}

Eterm nbif_impl_hipe_bifs_get_rts_param_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_get_rts_param_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_get_rts_param_1]);
}

Eterm nbif_impl_hipe_bifs_patch_insn_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_patch_insn_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_patch_insn_3]);
}

Eterm nbif_impl_hipe_bifs_patch_call_3(Process *c_p, Eterm *regs)
{
    return hipe_bifs_patch_call_3(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_patch_call_3]);
}

Eterm nbif_impl_hipe_bifs_add_ref_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_add_ref_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_add_ref_2]);
}

Eterm nbif_impl_hipe_bifs_alloc_loader_state_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_alloc_loader_state_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_alloc_loader_state_1]);
}

Eterm nbif_impl_hipe_bifs_call_count_on_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_call_count_on_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_call_count_on_1]);
}

Eterm nbif_impl_hipe_bifs_call_count_off_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_call_count_off_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_call_count_off_1]);
}

Eterm nbif_impl_hipe_bifs_call_count_get_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_call_count_get_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_call_count_get_1]);
}

Eterm nbif_impl_hipe_bifs_call_count_clear_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_call_count_clear_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_call_count_clear_1]);
}

Eterm nbif_impl_hipe_bifs_trap_count_get_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_trap_count_get_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_trap_count_get_0]);
}

Eterm nbif_impl_hipe_bifs_trap_count_clear_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_trap_count_clear_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_trap_count_clear_0]);
}

Eterm nbif_impl_hipe_bifs_show_estack_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_show_estack_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_show_estack_1]);
}

Eterm nbif_impl_hipe_bifs_show_heap_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_show_heap_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_show_heap_1]);
}

Eterm nbif_impl_hipe_bifs_show_nstack_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_show_nstack_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_show_nstack_1]);
}

Eterm nbif_impl_hipe_bifs_nstack_used_size_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_nstack_used_size_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_nstack_used_size_0]);
}

Eterm nbif_impl_hipe_bifs_show_pcb_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_show_pcb_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_show_pcb_1]);
}

Eterm nbif_impl_hipe_bifs_show_term_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_show_term_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_show_term_1]);
}

Eterm nbif_impl_hipe_bifs_in_native_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_in_native_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_in_native_0]);
}

Eterm nbif_impl_hipe_bifs_modeswitch_debug_on_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_modeswitch_debug_on_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_modeswitch_debug_on_0]);
}

Eterm nbif_impl_hipe_bifs_modeswitch_debug_off_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_modeswitch_debug_off_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_modeswitch_debug_off_0]);
}

Eterm nbif_impl_hipe_bifs_debug_native_called_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_debug_native_called_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_debug_native_called_2]);
}

Eterm nbif_impl_hipe_bifs_llvm_fix_pinned_regs_0(Process *c_p, Eterm *regs)
{
    return hipe_bifs_llvm_fix_pinned_regs_0(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_llvm_fix_pinned_regs_0]);
}

Eterm nbif_impl_hipe_bifs_build_stacktrace_1(Process *c_p, Eterm *regs)
{
    return hipe_bifs_build_stacktrace_1(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_build_stacktrace_1]);
}

Eterm nbif_impl_hipe_bifs_write_u64_2(Process *c_p, Eterm *regs)
{
    return hipe_bifs_write_u64_2(c_p, regs, (UWord *) bif_export[BIF_hipe_bifs_write_u64_2]);
}

